import type { MarketplaceProductDetails, SimilarMarketplaceProduct } from "@/components/marketplace/product-details/marketplace-product-details.types";

export const PRODUCT_IMAGE_FALLBACK = "/images/farmer/create-listing/placeholders/listing-photo-placeholder-1.jpg";

export const MARKETPLACE_PRODUCT_DETAILS: MarketplaceProductDetails = {
  id: "fresh-organic-tomatoes",
  farmerId: "farmer-1",
  title: "Fresh Organic Tomatoes",
  category: "Vegetables",
  farmerName: "Al-Nour Farm",
  verifiedFarmer: true,
  rating: 4.8,
  reviewsCount: 128,
  price: 12,
  currency: "USD",
  unit: "kg",
  availableQuantity: "500 kg",
  harvestDate: "May 20, 2025",
  location: "Gaza, Palestine",
  grade: "Grade A",
  listingType: "Spot Available Now",
  description:
    "Our fresh organic tomatoes are grown with care using natural farming practices. Handpicked at peak ripeness to ensure the best flavor, color, and nutrition. Ideal for salads, cooking, and processing.",
  images: [
    "/images/marketplace/tomato1.jpg",
    "/images/marketplace/tomato2.jpg",
    "/images/marketplace/tomato3.jpg",
    "/images/marketplace/tomato4.jpg",
    "/images/marketplace/tomato5.jpg",
    "/images/marketplace/tomato6.jpg",
    "/images/marketplace/tomatoes.jpg",
  ],
  details: {
    productType: "Fresh Tomatoes",
    variety: "Beefsteak",
    grade: "A",
    farmingMethod: "Organic",
    packaging: "Plastic Crates (10 kg)",
    shelfLife: "7-10 Days",
    storage: "Keep in a cool place",
    certifications: "Organic Certified",
  },
};

export const SIMILAR_MARKETPLACE_PRODUCTS: SimilarMarketplaceProduct[] = [
  {
    id: "vine-ripened-tomatoes",
    title: "Vine Ripened Tomatoes",
    farmerName: "Green Valley Farm",
    verifiedFarmer: true,
    rating: 4.7,
    reviewsCount: 96,
    price: 11,
    currency: "USD",
    unit: "kg",
    availableQuantity: "400 kg available",
    image: "/images/marketplace/vine2.jpg",
  },
  {
    id: "cherry-tomatoes",
    title: "Cherry Tomatoes",
    farmerName: "Sunrise Farm",
    verifiedFarmer: true,
    rating: 4.9,
    reviewsCount: 74,
    price: 14,
    currency: "USD",
    unit: "kg",
    availableQuantity: "250 kg available",
    image: "/images/marketplace/cherryTomato.jpg",
  },
  {
    id: "roma-tomatoes",
    title: "Roma Tomatoes",
    farmerName: "Al Wafa Farm",
    verifiedFarmer: true,
    rating: 4.6,
    reviewsCount: 58,
    price: 10,
    currency: "USD",
    unit: "kg",
    availableQuantity: "600 kg available",
    image: "/images/marketplace/roma2.jpg",
  },
];
