/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */
import { Product } from '../types/types';

export const PRODUCTS: Product[] = [
  
  {
    id: 'fresh-organic-tomatoes',
    titleEn: 'Fresh Organic Tomatoes',
    titleAr: 'طماطم عضوية طازجة',
    farmEn: 'Al-Nour Farm',
    farmAr: 'مزرعة النور',
    farmRating: 4.8,
    farmReviewsCount: 128,
    priceUsd: 12,
    quantityAvailable: 500,
    harvestDate: 'May 20, 2026',
    harvestDateAr: '٢٠ مايو ٢٠٢٦',
    locationEn: 'Gaza, Palestine',
    locationAr: 'غزة، فلسطين',
    gradeEn: 'Grade A',
    gradeAr: 'درجة أ',
    isSpotAvailable: true,
    descriptionEn: 'Our fresh organic tomatoes are grown with care using natural farming practices. Handpicked at peak ripeness to ensure the best flavor, color, and nutrition. Ideal for salads, cooking, and processing.',
    descriptionAr: 'تُزرع الطماطم العضوية الطازجة لدينا بعناية فائقة باستخدام ممارسات زراعية طبيعية ١٠٠٪. تُقطف يدوياً في ذروة نضجها لضمان الحصول على أفضل نكهة ولون وقيمة غذائية. مثالية للسلطات والطهي والتصنيع.',
    images: [
  '/images/marketplace/tomato1.jpg',
  '/images/marketplace/tomato2.jpg',
  '/images/marketplace/tomato3.jpg',
  '/images/marketplace/tomato4.jpg',
  '/images/marketplace/tomato5.jpg',
  '/images/marketplace/tomato6.jpg',
],
    verifiedFarmer: true,
    specs: {
      productTypeEn: 'Fresh Tomatoes',
      productTypeAr: 'طماطم طازجة',
      varietyEn: 'Beefsteak',
      varietyAr: 'بيف ستيك',
      gradeEn: 'A',
      gradeAr: 'أ',
      farmingMethodEn: 'Organic',
      farmingMethodAr: 'عضوي',
      packagingEn: 'Plastic Crates (10 kg)',
      packagingAr: 'صناديق بلاستيكية (١٠ كجم)',
      shelfLifeEn: '7-10 Days',
      shelfLifeAr: '٧-١٠ أيام',
      storageEn: 'Keep in a cool place',
      storageAr: 'يُحفظ في مكان بارد',
      certificationsEn: 'Organic Certified',
      certificationsAr: 'شهادة العضوية المعتمدة'
    },
    reviews: [
      {
        id: 'r1',
        userNameEn: 'Yousef Hassan',
        userNameAr: 'يوسف حسن',
        rating: 5,
        date: 'June 12, 2026',
        dateAr: '١٢ يونيو ٢٠٢٦',
        commentEn: 'Amazing quality! The tomatoes are firm, juicy, and very sweet. Perfect shipment and carefully packed.',
        commentAr: 'جودة مذهلة! الطماطم متماسكة، مليئة بالعصارة، وحلوة المذاق جداً. الشحنة ممتازة ومغلفة بعناية.'
      },
      {
        id: 'r2',
        userNameEn: 'Mariam Ali',
        userNameAr: 'مريم علي',
        rating: 4,
        date: 'May 28, 2026',
        dateAr: '٢٨ مايو ٢٠٢٦',
        commentEn: 'Very fresh and clean. Highly recommended for commercial restaurants looking for reliable organic produce.',
        commentAr: 'طازجة جداً ونظيفة. نوصي بها بشدة للمطاعم التجارية التي تبحث عن منتجات عضوية موثوقة.'
      }
    ]
  },
  {
    id: 'vine-ripened-tomatoes',
    titleEn: 'Vine Ripened Tomatoes',
    titleAr: 'طماطم ناضجة على الغصن',
    farmEn: 'Green Valley Farm',
    farmAr: 'مزرعة الوادي الأخضر',
    farmRating: 4.7,
    farmReviewsCount: 91,
    priceUsd: 11,
    quantityAvailable: 400,
    harvestDate: 'June 15, 2026',
    harvestDateAr: '١٥ يونيو ٢٠٢٦',
    locationEn: 'Al Ain, UAE',
    locationAr: 'العين، الإمارات',
    gradeEn: 'Grade A',
    gradeAr: 'درجة أ',
    isSpotAvailable: true,
    descriptionEn: 'Succulent and sweet, these vine-ripened tomatoes are harvested with their stems attached to preserve freshness and aroma. Perfect for gourmet dishes and roasting.',
    descriptionAr: 'طماطم ناضجة على الغصن، تتميز بنكهتها الغنية والحلوة، تُقطف مع سيقانها للحفاظ على نضارتها ورائحتها المميزة. مثالية للأطباق الفاخرة والشواء.',
    images: [
     '/images/marketplace/vine2.jpg', // tomatoes on stem
    '/images/marketplace/vine1.jpg',   // basket
    '/images/marketplace/vine3.jpg'
    ],
    verifiedFarmer: true,
    specs: {
      productTypeEn: 'Vine Ripened Tomatoes',
      productTypeAr: 'طماطم غصن ناضجة',
      varietyEn: 'Campari',
      varietyAr: 'كامباري',
      gradeEn: 'A',
      gradeAr: 'أ',
      farmingMethodEn: 'Hydroponic',
      farmingMethodAr: 'زراعة مائية',
      packagingEn: 'Cardboard Boxes (5 kg)',
      packagingAr: 'صناديق كرتونية (٥ كجم)',
      shelfLifeEn: '10-14 Days',
      shelfLifeAr: '١٠-١٤ يوماً',
      storageEn: 'Room temperature',
      storageAr: 'درجة حرارة الغرفة',
      certificationsEn: 'GlobalGAP Certified',
      certificationsAr: 'شهادة جودة غلوبال غاب'
    },
    reviews: [
      {
        id: 'r3',
        userNameEn: 'Ahmad Mansour',
        userNameAr: 'أحمد منصور',
        rating: 5,
        date: 'June 20, 2026',
        dateAr: '٢٠ يونيو ٢٠٢٦',
        commentEn: 'Perfect flavor and beautiful presentation. Stems are completely fresh, green, and smells great.',
        commentAr: 'نكهة مثالية وعرض جميل جداً. الأغصان طازجة تماماً وخضراء ورائحتها رائعة.'
      }
    ]
  },
  {
    id: 'cherry-tomatoes',
    titleEn: 'Sweet Cherry Tomatoes',
    titleAr: 'طماطم كرزية حلوة',
    farmEn: 'Sunrise Farm',
    farmAr: 'مزرعة شروق الشمس',
    farmRating: 4.9,
    farmReviewsCount: 74,
    priceUsd: 14,
    quantityAvailable: 250,
    harvestDate: 'June 28, 2026',
    harvestDateAr: '٢٨ يونيو ٢٠٢٦',
    locationEn: 'Jerash, Jordan',
    locationAr: 'جرش، الأردن',
    gradeEn: 'Premium Grade',
    gradeAr: 'درجة ممتازة',
    isSpotAvailable: true,
    descriptionEn: 'Bite-sized explosions of intense sweetness. These cherry tomatoes are grown under perfect sunny conditions, yielding a thin skin and vibrant red color. Excellent for snacking, salads, or pasta.',
    descriptionAr: 'انفجار من الحلاوة المكثفة في كل حبة صغيرة. تُزرع هذه الطماطم الكرزية تحت أشعة الشمس المثالية، مما ينتج عنه قشرة رقيقة ولون أحمر زاهٍ. ممتازة للوجبات الخفيفة أو السلطات أو الباستا.',
    images: [ 
    '/images/marketplace/cherryTomato.jpg',
    '/images/marketplace/cherrytomato1.jpg',  
    '/images/marketplace/cherryTomato.jpg'    
    ],
    verifiedFarmer: true,
    specs: {
      productTypeEn: 'Cherry Tomatoes',
      productTypeAr: 'طماطم كرزية',
      varietyEn: 'Sweet Million',
      varietyAr: 'سويت مِليون',
      gradeEn: 'Premium',
      gradeAr: 'ممتاز',
      farmingMethodEn: 'Greenhouse Organic',
      farmingMethodAr: 'دفيئة زراعية عضوية',
      packagingEn: 'Clamshell Punnets (250g)',
      packagingAr: 'عبوات شفافة بوزن 250 جرام',
      shelfLifeEn: '8-12 Days',
      shelfLifeAr: '٨-١٢ يوماً',
      storageEn: 'Cool, dry place',
      storageAr: 'مكان بارد وجاف',
      certificationsEn: 'USDA Organic',
      certificationsAr: 'شهادة العضوية الأمريكية USDA'
    },
    reviews: [
      {
        id: 'r4',
        userNameEn: 'Layla Qasem',
        userNameAr: 'ليلى قاسم',
        rating: 5,
        date: 'June 29, 2026',
        dateAr: '٢٩ يونيو ٢٠٢٦',
        commentEn: 'Incredibly sweet! My children love them as snacks. Best cherry tomatoes on the market.',
        commentAr: 'حلوة المذاق بشكل لا يصدق! يحبها أطفالي كوجبة خفيفة. أفضل طماطم كرزية في السوق.'
      }
    ]
  },
  {
    id: 'roma-tomatoes',
    titleEn: 'Roma Plum Tomatoes',
    titleAr: 'طماطم روما البيضاوية',
    farmEn: 'Al Wafa Farm',
    farmAr: 'مزرعة الوفاء',
    farmRating: 4.6,
    farmReviewsCount: 58,
    priceUsd: 10,
    quantityAvailable: 600,
    harvestDate: 'May 12, 2026',
    harvestDateAr: '١٢ مايو ٢٠٢٦',
    locationEn: 'Hebron, Palestine',
    locationAr: 'الخليل، فلسطين',
    gradeEn: 'Grade A',
    gradeAr: 'درجة أ',
    isSpotAvailable: true,
    descriptionEn: 'Firm, meaty, and low in moisture, our Roma tomatoes are the gold standard for sauces, pastes, and canning. Grown using traditional agricultural heritage.',
    descriptionAr: 'متماسكة، غنية باللحم، ومنخفضة الرطوبة، طماطم روما لدينا هي المعيار الذهبي للصلصات والمعجون والتعليب. تُزرع باستخدام التراث الزراعي العريق والتقليدي.',
    images: [
     '/images/marketplace/roma2.jpg', 
    '/images/marketplace/roma1.jpg',   
    '/images/marketplace/roma3.jpg'    
    ],
    verifiedFarmer: true,
    specs: {
      productTypeEn: 'Roma Tomatoes',
      productTypeAr: 'طماطم روما',
      varietyEn: 'Plum Roma',
      varietyAr: 'بلوم روما',
      gradeEn: 'A',
      gradeAr: 'أ',
      farmingMethodEn: 'Open Field',
      farmingMethodAr: 'حقل مفتوح',
      packagingEn: 'Wooden Crates (15 kg)',
      packagingAr: 'صناديق خشبية (١٥ كجم)',
      shelfLifeEn: '12-15 Days',
      shelfLifeAr: '١٢-١٥ يوماً',
      storageEn: 'Cool, well-ventilated area',
      storageAr: 'مكان بارد وتهوية جيدة',
      certificationsEn: 'Local Farmer Association',
      certificationsAr: 'شهادة جمعية المزارعين المحلية'
    },
    reviews: [
      {
        id: 'r5',
        userNameEn: 'Tareq Mahmoud',
        userNameAr: 'طارق محمود',
        rating: 4,
        date: 'May 18, 2026',
        dateAr: '١٨ مايو ٢٠٢٦',
        commentEn: 'Made the best tomato paste ever with these! Very thick and rich flavor.',
        commentAr: 'صنعت بها أفضل معجون طماطم على الإطلاق! قوام كثيف ونكهة غنية جداً.'
      }
    ]
  },
  {
    id: 'premium-olives',
    titleEn: 'Premium Olives',
    titleAr: 'زيتون بلدي ممتاز',
    farmEn: 'Ajloun Heritage Farm',
    farmAr: 'مزرعة تراث عجلون',
    farmRating: 4.9,
    farmReviewsCount: 86,
    priceUsd: 1.25,
    quantityAvailable: 2000,
    harvestDate: 'June 1, 2026',
    harvestDateAr: '١ يونيو ٢٠٢٦',
    locationEn: 'Ajloun, Jordan',
    locationAr: 'عجلون، الأردن',
    gradeEn: 'Grade A',
    gradeAr: 'درجة أ',
    isSpotAvailable: true,
    descriptionEn: 'Premium handpicked olives from ancient olive groves of Ajloun, Jordan. Grown with traditional methods to preserve their pristine quality, robust flavor, and richness. Extremely rich in antioxidants and ideal for olive oil or pickling.',
    descriptionAr: 'زيتون بلدي ممتاز مقطوف يدوياً من كروم عجلون الأثرية في الأردن. يزرع بطرق تقليدية متوارثة للحفاظ على جودته العالية ونكهته الغنية وقيمته الغذائية. مثالي للتخليل أو لإنتاج زيت زيتون فاخر وعالي الجودة.',
    images: [
      '/images/marketplace/olives.jpg',
      '/images/marketplace/olives2.jpg'
    ],
    verifiedFarmer: true,
    specs: {
      productTypeEn: 'Premium Olives',
      productTypeAr: 'زيتون بلدي',
      varietyEn: 'Nabali',
      varietyAr: 'نبالي بلدي',
      gradeEn: 'A',
      gradeAr: 'أ',
      farmingMethodEn: 'Traditional Rainfed',
      farmingMethodAr: 'بعلي تقليدي',
      packagingEn: 'Plastic Buckets (15 kg)',
      packagingAr: 'أوعية بلاستيكية (١٥ كجم)',
      shelfLifeEn: '30-45 Days',
      shelfLifeAr: '٣٠-٤٥ يوماً',
      storageEn: 'Keep in a dry, ventilated place',
      storageAr: 'يُحفظ في مكان جاف وجيد التهوية',
      certificationsEn: 'Certified Quality',
      certificationsAr: 'شهادة الجودة الأردنية'
    },
    reviews: [
      {
        id: 'r6',
        userNameEn: 'Samer Ibrahim',
        userNameAr: 'سامر إبراهيم',
        rating: 5,
        date: 'June 10, 2026',
        dateAr: '١٠ يونيو ٢٠٢٦',
        commentEn: 'Absolute premium quality! The olives are large, fresh, and very clean.',
        commentAr: 'جودة استثنائية! الحبات كبيرة ونظيفة وطازجة جداً. أنصح به بشدة.'
      }
    ]
  },
  {
    id: 'wheat-grains',
    titleEn: 'Golden Wheat Grains',
    titleAr: 'حبوب القمح الذهبي',
    farmEn: 'Sharjah Oasis Farms',
    farmAr: 'مزارع واحة الشارقة',
    farmRating: 4.7,
    farmReviewsCount: 42,
    priceUsd: 0.32,
    quantityAvailable: 20000,
    harvestDate: 'May 25, 2026',
    harvestDateAr: '٢٥ مايو ٢٠٢٦',
    locationEn: 'Sharjah, UAE',
    locationAr: 'الشارقة، الإمارات',
    gradeEn: 'Grade A',
    gradeAr: 'درجة أ',
    isSpotAvailable: true,
    descriptionEn: 'Pure and dried premium golden wheat grains harvested under perfect climatic conditions to guarantee the lowest level of moisture. Ground into clean flour of high nutritional value.',
    descriptionAr: 'حبوب قمح ذهبية نقية ومجففة بعناية فائقة، تم حصادها تحت ظروف مناخية مثالية لضمان أدنى مستويات الرطوبة. مثالي للطحن وصناعة الخبز الفاخر عالي القيمة الغذائية.',
    images: [
      '/images/marketplace/قمح.jpg',
      '/images/marketplace/قمح3.jpg'
    ],
    verifiedFarmer: true,
    specs: {
      productTypeEn: 'Wheat Grains',
      productTypeAr: 'حبوب القمح',
      varietyEn: 'Durum Wheat',
      varietyAr: 'قمح قاسي (ديورم)',
      gradeEn: 'A',
      gradeAr: 'أ',
      farmingMethodEn: 'Irrigated Cultivation',
      farmingMethodAr: 'زراعة مروية مستدامة',
      packagingEn: 'Jute Sacks (50 kg)',
      packagingAr: 'أكياس خيش (٥٠ كجم)',
      shelfLifeEn: '365 Days',
      shelfLifeAr: 'عام كامل',
      storageEn: 'Dry silo or ventilated warehouse',
      storageAr: 'صوامع جافة أو مستودعات جيدة التهوية',
      certificationsEn: 'SGS Quality Certified',
      certificationsAr: 'شهادة جودة SGS العالمية'
    },
    reviews: [
      {
        id: 'r7',
        userNameEn: 'Khaled Omar',
        userNameAr: 'خالد عمر',
        rating: 5,
        date: 'June 5, 2026',
        dateAr: '٥ يونيو ٢٠٢٦',
        commentEn: 'Cleanest wheat grains I have ever purchased. Dryness and purity levels are perfect.',
        commentAr: 'أنظف حبوب قمح قمت بشرائها على الإطلاق. درجة الجفاف والنقاء مثالية جداً.'
      }
    ]
  },
  {
    id: 'fresh-citrus',
    titleEn: 'Fresh Valencia Citrus',
    titleAr: 'حمضيات فالنسيا الطازجة',
    farmEn: 'Valencia Sunny Orchards',
    farmAr: 'بساتين فالنسيا المشمسة',
    farmRating: 4.8,
    farmReviewsCount: 154,
    priceUsd: 0.60,
    quantityAvailable: 3500,
    harvestDate: 'May 10, 2026',
    harvestDateAr: '١٠ مايو ٢٠٢٦',
    locationEn: 'Valencia, Spain',
    locationAr: 'فالنسيا، إسبانيا',
    gradeEn: 'Grade A',
    gradeAr: 'درجة أ',
    isSpotAvailable: true,
    descriptionEn: 'Bright, extremely juicy and sweet Valencia oranges. Ideal for squeezing and fresh juices, rich in Vitamin C. Handpicked from solar-exposed Mediterranean orchards to maximize taste.',
    descriptionAr: 'برتقال فالنسيا الزاهي المليء بالعصارة الفائقة والمذاق الحلو اللذيذ. غني بفيتامين ج ومثالي للعصائر الطبيعية الطازجة. مقطوف يدوياً من بساتين البحر الأبيض المتوسط المشمسة.',
    images: [
      'https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1582979512210-99b6a53386f9?w=800&auto=format&fit=crop&q=80'
    ],
    verifiedFarmer: true,
    specs: {
      productTypeEn: 'Valencia Citrus',
      productTypeAr: 'برتقال فالنسيا',
      varietyEn: 'Valencia Late',
      varietyAr: 'فالنسيا المتأخر',
      gradeEn: 'A',
      gradeAr: 'أ',
      farmingMethodEn: 'Sunny Orchards',
      farmingMethodAr: 'بساتين مشمسة طبيعية',
      packagingEn: 'Cardboard Boxes (15 kg)',
      packagingAr: 'صناديق كرتونية (١٥ كجم)',
      shelfLifeEn: '14-20 Days',
      shelfLifeAr: '١٤-٢٠ يوماً',
      storageEn: 'Keep in a cold storage or refrigerator',
      storageAr: 'يُحفظ في مكان بارد أو في المبرد',
      certificationsEn: 'EuroGAP Certified',
      certificationsAr: 'شهادة الجودة الأوروبية EuroGAP'
    },
    reviews: [
      {
        id: 'r8',
        userNameEn: 'Elena Gomez',
        userNameAr: 'إيلينا غوميز',
        rating: 5,
        date: 'May 15, 2026',
        dateAr: '١٥ مايو ٢٠٢٦',
        commentEn: 'Unbelievably juicy! Customers at our juice bar love these oranges.',
        commentAr: 'مليء بالعصارة بشكل لا يصدق! زبائن متجرنا للعصائر يعشقون هذا البرتقال.'
      }
    ]
  }
];

export const TRANSLATIONS = {
  en: {
    logoText: 'AgriBridge',
    howItWorks: 'How It Works',
    faq: 'FAQ',
    marketplace: 'Marketplace',
    rfq: 'RFQ',
    login: 'Login',
    getStarted: 'Get Started',
    backToMarketplace: 'Back to Marketplace',
    verifiedFarmer: 'Verified Farmer',
    productsFound: 'products found',
    quantity: 'QUANTITY',
    location: 'LOCATION',
    viewDetails: 'View Details',
    harvestDate: 'HARVEST DATE',
    available: 'Available',
    requestQuote: 'Request Quote',
    saveListing: 'Save Listing',
    messageFarmer: 'Message Farmer',
    detailsTab: 'Details',
    farmerProfileTab: 'Farmer Profile',
    reviewsTab: 'Reviews',
    similarProducts: 'Similar Products',
    viewAll: 'View All',
    searchPlaceholder: 'Search fresh produce...',
    allLocations: 'All Locations',
    grade: 'Grade',
    spot: 'Spot',
    availableNow: 'Available Now',
    specs: {
      productType: 'PRODUCT TYPE',
      variety: 'VARIETY',
      grade: 'GRADE',
      farmingMethod: 'FARMING METHOD',
      packaging: 'PACKAGING',
      shelfLife: 'SHELF LIFE',
      storage: 'STORAGE',
      certifications: 'CERTIFICATIONS'
    },
    farmerProfile: {
      aboutFarm: 'About the Farm',
      contactFarmer: 'Contact the Farmer',
      phone: 'Phone',
      email: 'Email',
      experience: 'Experience',
      years: 'years in farming',
      certifiedLogo: 'Certified Organic Practice'
    },
    quoteModal: {
      title: 'Request a Quote',
      desc: 'Send a quotation request directly to the farmer. They will respond shortly with terms.',
      quantity: 'Required Quantity (kg)',
      targetPrice: 'Target Price (USD/kg)',
      deliveryDate: 'Requested Delivery Date',
      notes: 'Additional notes or requirements',
      send: 'Send Quotation Request',
      success: 'Quotation request sent successfully to the farmer!'
    },
    messageModal: {
      title: 'Message Farmer',
      desc: 'Send a direct message to the farmer about this listing.',
      subject: 'Subject',
      message: 'Your Message',
      send: 'Send Message',
      success: 'Message sent successfully to the farmer!'
    },
    savedToListing: 'Listing saved to favorites!',
    removedFromListing: 'Removed from favorites!'
  },
  ar: {
    logoText: 'أجري بريدج',
    howItWorks: 'كيف نعمل',
    faq: 'الأسئلة الشائعة',
    marketplace: 'السوق الإلكتروني',
    rfq: 'طلب عروض أسعار',
    login: 'تسجيل الدخول',
    getStarted: 'البدء الآن',
    backToMarketplace: 'العودة إلى السوق',
    verifiedFarmer: 'مزارع معتمد',
    productsFound: 'منتجات متوفرة',
    quantity: 'الكمية',
    location: 'الموقع',
    viewDetails: 'عرض التفاصيل',
    harvestDate: 'تاريخ الحصاد',
    available: 'متوفر',
    requestQuote: 'طلب تسعيرة',
    saveListing: 'حفظ العرض',
    messageFarmer: 'مراسلة المزارع',
    detailsTab: 'التفاصيل',
    farmerProfileTab: 'ملف المزارع',
    reviewsTab: 'التقييمات',
    similarProducts: 'منتجات مشابهة',
    viewAll: 'عرض الكل',
    searchPlaceholder: 'ابحث عن منتجات زراعية طازجة...',
    allLocations: 'كل المواقع',
    grade: 'درجة',
    spot: 'فوري',
    availableNow: 'متوفر الآن',
    specs: {
      productType: 'نوع المنتج',
      variety: 'الصنف',
      grade: 'الدرجة',
      farmingMethod: 'طريقة الزراعة',
      packaging: 'التعبئة والتغليف',
      shelfLife: 'مدة الصلاحية',
      storage: 'طريقة التخزين',
      certifications: 'الشهادات المعتمدة'
    },
    farmerProfile: {
      aboutFarm: 'عن المزرعة',
      contactFarmer: 'تواصل مباشر مع المزارع',
      phone: 'رقم الهاتف',
      email: 'البريد الإلكتروني',
      experience: 'الخبرة',
      years: 'سنوات في الزراعة',
      certifiedLogo: 'ممارسات عضوية معتمدة'
    },
    quoteModal: {
      title: 'تقديم طلب تسعير',
      desc: 'أرسل طلباً للحصول على تسعيرة مباشرة من المزارع. سيتواصل معك المزارع قريباً.',
      quantity: 'الكمية المطلوبة (كجم)',
      targetPrice: 'السعر المستهدف (دولار/كجم)',
      deliveryDate: 'تاريخ التسليم المطلوب',
      notes: 'ملاحظات أو متطلبات إضافية',
      send: 'إرسال طلب التسعيرة',
      success: 'تم إرسال طلب التسعيرة بنجاح للمزارع!'
    },
    messageModal: {
      title: 'مراسلة المزارع',
      desc: 'أرسل رسالة مباشرة إلى المزارع للاستفسار عن هذا المحصول.',
      subject: 'الموضوع',
      message: 'رسالتك',
      send: 'إرسال الرسالة',
      success: 'تم إرسال رسالتك بنجاح للمزارع!'
    },
    savedToListing: 'تم حفظ العرض في المفضلة!',
    removedFromListing: 'تمت إزالة العرض من المفضلة!'
  }
};
