import type {
  AdminDashboardStats,
  BuyerProfile,
  Deal,
  Dispute,
  FarmerProfile,
  Inspection,
  Listing,
  RFQ,
  Review,
  User,
} from "@/types";

export const farmers: User[] = [
  {
    id: "farmer-1",
    name: "Maha Al-Khalil",
    email: "maha@valleyharvest.example",
    role: "farmer",
    phone: "+970 599 111 204",
    location: "Jenin, Palestine",
    status: "active",
    joinedAt: "2025-01-12",
  },
  {
    id: "farmer-2",
    name: "Omar Nassar",
    email: "omar@olivegrove.example",
    role: "farmer",
    phone: "+970 599 221 408",
    location: "Nablus, Palestine",
    status: "active",
    joinedAt: "2025-02-03",
  },
  {
    id: "farmer-3",
    name: "Rana Haddad",
    email: "rana@freshfields.example",
    role: "farmer",
    phone: "+970 599 331 572",
    location: "Tulkarm, Palestine",
    status: "active",
    joinedAt: "2025-03-18",
  },
  {
    id: "farmer-4",
    name: "Yousef Darwish",
    email: "yousef@citrusline.example",
    role: "farmer",
    phone: "+970 599 441 739",
    location: "Jericho, Palestine",
    status: "pending",
    joinedAt: "2025-04-22",
  },
  {
    id: "farmer-5",
    name: "Lina Abu Zaid",
    email: "lina@sunfarm.example",
    role: "farmer",
    phone: "+970 599 551 862",
    location: "Hebron, Palestine",
    status: "active",
    joinedAt: "2025-05-07",
  },
];

export const buyers: User[] = [
  {
    id: "buyer-1",
    name: "Samir Qassis",
    email: "samir@urbanplate.example",
    role: "buyer",
    phone: "+970 598 210 145",
    location: "Ramallah, Palestine",
    status: "active",
    joinedAt: "2025-01-27",
  },
  {
    id: "buyer-2",
    name: "Dalia Mansour",
    email: "dalia@goldenfoods.example",
    role: "buyer",
    phone: "+970 598 310 248",
    location: "Bethlehem, Palestine",
    status: "active",
    joinedAt: "2025-02-19",
  },
  {
    id: "buyer-3",
    name: "Karim Saliba",
    email: "karim@levantwholesale.example",
    role: "buyer",
    phone: "+970 598 410 363",
    location: "Jerusalem, Palestine",
    status: "active",
    joinedAt: "2025-03-11",
  },
  {
    id: "buyer-4",
    name: "Nour Daraghmeh",
    email: "nour@exporthub.example",
    role: "buyer",
    phone: "+970 598 510 474",
    location: "Gaza, Palestine",
    status: "pending",
    joinedAt: "2025-04-02",
  },
  {
    id: "buyer-5",
    name: "Tareq Khoury",
    email: "tareq@farmfreshco.example",
    role: "buyer",
    phone: "+970 598 610 585",
    location: "Haifa, Palestine",
    status: "active",
    joinedAt: "2025-05-15",
  },
];

export const qualityOfficers: User[] = [
  {
    id: "officer-1",
    name: "Hiba Saleh",
    email: "hiba@agribridge.example",
    role: "quality_officer",
    phone: "+970 597 700 101",
    location: "Ramallah, Palestine",
    status: "active",
    joinedAt: "2025-01-05",
  },
  {
    id: "officer-2",
    name: "Nader Tamimi",
    email: "nader@agribridge.example",
    role: "quality_officer",
    phone: "+970 597 700 202",
    location: "Nablus, Palestine",
    status: "active",
    joinedAt: "2025-02-15",
  },
];

export const admins: User[] = [
  {
    id: "admin-1",
    name: "AgriBridge Admin",
    email: "admin@agribridge.example",
    role: "admin",
    phone: "+970 597 900 001",
    location: "Ramallah, Palestine",
    status: "active",
    joinedAt: "2024-12-01",
  },
];

export const users: User[] = [...farmers, ...buyers, ...qualityOfficers, ...admins];

export const farmerProfiles: FarmerProfile[] = [
  {
    userId: "farmer-1",
    farmName: "Valley Harvest Cooperative",
    farmSizeHectares: 22,
    primaryCrops: ["Tomatoes", "Cucumbers", "Bell peppers"],
    certifications: ["GlobalG.A.P. pending", "Organic transition"],
    yearsInBusiness: 9,
  },
  {
    userId: "farmer-2",
    farmName: "Nassar Olive Grove",
    farmSizeHectares: 31,
    primaryCrops: ["Olives", "Olive oil", "Almonds"],
    certifications: ["Organic"],
    yearsInBusiness: 18,
  },
  {
    userId: "farmer-3",
    farmName: "Fresh Fields Tulkarm",
    farmSizeHectares: 14,
    primaryCrops: ["Strawberries", "Lettuce", "Herbs"],
    certifications: ["Food safety audit"],
    yearsInBusiness: 6,
  },
  {
    userId: "farmer-4",
    farmName: "Citrus Line Farms",
    farmSizeHectares: 28,
    primaryCrops: ["Oranges", "Lemons", "Dates"],
    certifications: ["Export packhouse partner"],
    yearsInBusiness: 12,
  },
  {
    userId: "farmer-5",
    farmName: "Sun Farm Hebron",
    farmSizeHectares: 17,
    primaryCrops: ["Grapes", "Figs", "Apricots"],
    certifications: ["Local quality certificate"],
    yearsInBusiness: 7,
  },
];

export const buyerProfiles: BuyerProfile[] = [
  {
    userId: "buyer-1",
    companyName: "Urban Plate Restaurants",
    buyerType: "restaurant",
    monthlyPurchaseVolume: "18 tons",
    preferredCrops: ["Tomatoes", "Herbs", "Leafy greens"],
  },
  {
    userId: "buyer-2",
    companyName: "Golden Foods Factory",
    buyerType: "factory",
    monthlyPurchaseVolume: "55 tons",
    preferredCrops: ["Olives", "Peppers", "Citrus"],
  },
  {
    userId: "buyer-3",
    companyName: "Levant Wholesale Market",
    buyerType: "wholesaler",
    monthlyPurchaseVolume: "120 tons",
    preferredCrops: ["Cucumbers", "Potatoes", "Tomatoes"],
  },
  {
    userId: "buyer-4",
    companyName: "Export Hub Logistics",
    buyerType: "exporter",
    monthlyPurchaseVolume: "90 tons",
    preferredCrops: ["Dates", "Grapes", "Olive oil"],
  },
  {
    userId: "buyer-5",
    companyName: "FarmFresh Local Co.",
    buyerType: "local_company",
    monthlyPurchaseVolume: "34 tons",
    preferredCrops: ["Figs", "Strawberries", "Apricots"],
  },
];

export const listings: Listing[] = [
  {
    id: "listing-1",
    farmerId: "farmer-1",
    title: "Premium greenhouse tomatoes",
    type: "fresh_produce",
    crop: "Tomatoes",
    description: "Firm red tomatoes packed for restaurants and wholesale kitchens.",
    quantity: 12,
    unit: "ton",
    pricePerUnit: 780,
    currency: "USD",
    location: "Jenin, Palestine",
    harvestDate: "2026-06-20",
    availableFrom: "2026-06-22",
    status: "active",
    qualityGrade: "A",
    certifications: ["Pesticide residue tested"],
    imageUrl:
      "https://images.unsplash.com/photo-1592841200221-a6898f307baa?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "listing-2",
    farmerId: "farmer-2",
    title: "Cold-pressed extra virgin olive oil",
    type: "processed_goods",
    crop: "Olive oil",
    description: "New season olive oil in food-service tins, acidity below 0.8%.",
    quantity: 2400,
    unit: "liter",
    pricePerUnit: 5.4,
    currency: "USD",
    location: "Nablus, Palestine",
    harvestDate: "2026-05-29",
    availableFrom: "2026-06-18",
    status: "active",
    qualityGrade: "A",
    certifications: ["Organic"],
    imageUrl:
      "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "listing-3",
    farmerId: "farmer-3",
    title: "Fresh strawberries for retail packing",
    type: "fresh_produce",
    crop: "Strawberries",
    description: "Sweet strawberries sorted in crates for same-day distribution.",
    quantity: 520,
    unit: "crate",
    pricePerUnit: 8.75,
    currency: "USD",
    location: "Tulkarm, Palestine",
    harvestDate: "2026-06-16",
    availableFrom: "2026-06-17",
    status: "reserved",
    qualityGrade: "A",
    certifications: ["Food safety audit"],
    imageUrl:
      "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "listing-4",
    farmerId: "farmer-4",
    title: "Export-grade medjool dates",
    type: "fresh_produce",
    crop: "Dates",
    description: "Large medjool dates sorted by size and ready for export inspection.",
    quantity: 8,
    unit: "ton",
    pricePerUnit: 3100,
    currency: "USD",
    location: "Jericho, Palestine",
    harvestDate: "2026-06-10",
    availableFrom: "2026-06-25",
    status: "active",
    qualityGrade: "B",
    certifications: ["Export packhouse partner"],
    imageUrl:
      "https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "listing-5",
    farmerId: "farmer-5",
    title: "Table grapes in 5kg boxes",
    type: "fresh_produce",
    crop: "Grapes",
    description: "Crisp green grapes packed in ventilated boxes for local companies.",
    quantity: 1400,
    unit: "box",
    pricePerUnit: 6.2,
    currency: "USD",
    location: "Hebron, Palestine",
    harvestDate: "2026-06-28",
    availableFrom: "2026-06-30",
    status: "active",
    qualityGrade: "A",
    certifications: ["Local quality certificate"],
    imageUrl:
      "https://images.unsplash.com/photo-1537640538966-79f369143f8f?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "listing-6",
    farmerId: "farmer-1",
    title: "Cucumbers for processing",
    type: "fresh_produce",
    crop: "Cucumbers",
    description: "Uniform cucumbers suitable for pickling and food factory use.",
    quantity: 18,
    unit: "ton",
    pricePerUnit: 470,
    currency: "USD",
    location: "Jenin, Palestine",
    harvestDate: "2026-06-19",
    availableFrom: "2026-06-21",
    status: "active",
    qualityGrade: "B",
    certifications: ["Pesticide residue tested"],
    imageUrl:
      "https://images.unsplash.com/photo-1604977042946-1eecc30f269e?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "listing-7",
    farmerId: "farmer-3",
    title: "Mixed culinary herbs",
    type: "fresh_produce",
    crop: "Mint, parsley, coriander",
    description: "Washed bundles for restaurants, packed in reusable crates.",
    quantity: 360,
    unit: "crate",
    pricePerUnit: 5.5,
    currency: "USD",
    location: "Tulkarm, Palestine",
    harvestDate: "2026-06-17",
    availableFrom: "2026-06-18",
    status: "active",
    qualityGrade: "A",
    certifications: ["Food safety audit"],
    imageUrl:
      "https://images.unsplash.com/photo-1515586000433-45406d8e6662?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "listing-8",
    farmerId: "farmer-4",
    title: "Fresh Valencia oranges",
    type: "fresh_produce",
    crop: "Oranges",
    description: "Juice-grade oranges with strong brix values for factories.",
    quantity: 25,
    unit: "ton",
    pricePerUnit: 520,
    currency: "USD",
    location: "Jericho, Palestine",
    harvestDate: "2026-06-12",
    availableFrom: "2026-06-18",
    status: "sold",
    qualityGrade: "B",
    certifications: ["Export packhouse partner"],
    imageUrl:
      "https://images.unsplash.com/photo-1547514701-42782101795e?auto=format&fit=crop&w=900&q=80",
  },
];

export const rfqs: RFQ[] = [
  {
    id: "rfq-1",
    buyerId: "buyer-1",
    title: "Weekly tomato supply for restaurant group",
    crop: "Tomatoes",
    quantity: 3000,
    unit: "kg",
    targetPrice: 0.85,
    currency: "USD",
    deliveryLocation: "Ramallah, Palestine",
    deadline: "2026-06-24",
    status: "open",
    createdAt: "2026-06-12",
    notes: "Preference for Grade A greenhouse tomatoes in 10kg crates.",
    quotes: [
      {
        id: "quote-1",
        rfqId: "rfq-1",
        farmerId: "farmer-1",
        pricePerUnit: 0.82,
        totalPrice: 2460,
        currency: "USD",
        message: "Can deliver in two batches this week.",
        status: "submitted",
        createdAt: "2026-06-13",
      },
    ],
  },
  {
    id: "rfq-2",
    buyerId: "buyer-2",
    title: "Bulk cucumbers for pickling line",
    crop: "Cucumbers",
    quantity: 12,
    unit: "ton",
    targetPrice: 450,
    currency: "USD",
    deliveryLocation: "Bethlehem, Palestine",
    deadline: "2026-06-21",
    status: "quoted",
    createdAt: "2026-06-10",
    notes: "Uniform size requested, factory pickup possible.",
    quotes: [
      {
        id: "quote-2",
        rfqId: "rfq-2",
        farmerId: "farmer-1",
        pricePerUnit: 465,
        totalPrice: 5580,
        currency: "USD",
        message: "Available from June 21 after final sorting.",
        status: "submitted",
        createdAt: "2026-06-11",
      },
    ],
  },
  {
    id: "rfq-3",
    buyerId: "buyer-3",
    title: "Wholesale herbs contract",
    crop: "Mint and parsley",
    quantity: 200,
    unit: "crate",
    targetPrice: 5,
    currency: "USD",
    deliveryLocation: "Jerusalem, Palestine",
    deadline: "2026-06-28",
    status: "open",
    createdAt: "2026-06-13",
    notes: "Recurring weekly need for hotels and catering customers.",
    quotes: [],
  },
  {
    id: "rfq-4",
    buyerId: "buyer-4",
    title: "Export-ready dates",
    crop: "Medjool dates",
    quantity: 5,
    unit: "ton",
    targetPrice: 2950,
    currency: "USD",
    deliveryLocation: "Ashdod export warehouse",
    deadline: "2026-07-02",
    status: "matched",
    createdAt: "2026-06-05",
    notes: "Requires inspection report and export-grade packaging.",
    quotes: [
      {
        id: "quote-3",
        rfqId: "rfq-4",
        farmerId: "farmer-4",
        pricePerUnit: 3025,
        totalPrice: 15125,
        currency: "USD",
        message: "Packaging available through partner packhouse.",
        status: "accepted",
        createdAt: "2026-06-06",
      },
    ],
  },
  {
    id: "rfq-5",
    buyerId: "buyer-5",
    title: "Seasonal fig supply",
    crop: "Figs",
    quantity: 450,
    unit: "box",
    targetPrice: 7.25,
    currency: "USD",
    deliveryLocation: "Haifa, Palestine",
    deadline: "2026-07-05",
    status: "open",
    createdAt: "2026-06-14",
    notes: "Local company looking for reliable summer supply.",
    quotes: [],
  },
];

export const deals: Deal[] = [
  {
    id: "deal-1",
    listingId: "listing-1",
    farmerId: "farmer-1",
    buyerId: "buyer-1",
    title: "Tomato supply for Urban Plate",
    quantity: 3000,
    unit: "kg",
    unitPrice: 0.82,
    totalValue: 2460,
    currency: "USD",
    status: "awaiting_inspection",
    deliveryDate: "2026-06-23",
    deliveryLocation: "Ramallah, Palestine",
    createdAt: "2026-06-13",
    payment: {
      id: "payment-1",
      dealId: "deal-1",
      amount: 2460,
      currency: "USD",
      status: "pending",
      escrowReference: "ESC-2026-001",
      createdAt: "2026-06-13",
    },
  },
  {
    id: "deal-2",
    rfqId: "rfq-4",
    farmerId: "farmer-4",
    buyerId: "buyer-4",
    title: "Medjool dates export order",
    quantity: 5,
    unit: "ton",
    unitPrice: 3025,
    totalValue: 15125,
    currency: "USD",
    status: "inspection_scheduled",
    deliveryDate: "2026-07-04",
    deliveryLocation: "Ashdod export warehouse",
    createdAt: "2026-06-06",
    payment: {
      id: "payment-2",
      dealId: "deal-2",
      amount: 15125,
      currency: "USD",
      status: "pending",
      escrowReference: "ESC-2026-002",
      createdAt: "2026-06-06",
    },
  },
  {
    id: "deal-3",
    listingId: "listing-2",
    farmerId: "farmer-2",
    buyerId: "buyer-2",
    title: "Olive oil tins for Golden Foods",
    quantity: 1600,
    unit: "liter",
    unitPrice: 5.35,
    totalValue: 8560,
    currency: "USD",
    status: "escrow_funded",
    deliveryDate: "2026-06-26",
    deliveryLocation: "Bethlehem, Palestine",
    createdAt: "2026-06-08",
    payment: {
      id: "payment-3",
      dealId: "deal-3",
      amount: 8560,
      currency: "USD",
      status: "escrow_funded",
      escrowReference: "ESC-2026-003",
      createdAt: "2026-06-08",
    },
  },
  {
    id: "deal-4",
    listingId: "listing-5",
    farmerId: "farmer-5",
    buyerId: "buyer-5",
    title: "Grape boxes for FarmFresh Local",
    quantity: 500,
    unit: "box",
    unitPrice: 6.1,
    totalValue: 3050,
    currency: "USD",
    status: "in_delivery",
    deliveryDate: "2026-06-18",
    deliveryLocation: "Haifa, Palestine",
    createdAt: "2026-06-09",
    payment: {
      id: "payment-4",
      dealId: "deal-4",
      amount: 3050,
      currency: "USD",
      status: "escrow_funded",
      escrowReference: "ESC-2026-004",
      createdAt: "2026-06-09",
    },
  },
  {
    id: "deal-5",
    listingId: "listing-8",
    farmerId: "farmer-4",
    buyerId: "buyer-2",
    title: "Juice oranges for processing",
    quantity: 20,
    unit: "ton",
    unitPrice: 515,
    totalValue: 10300,
    currency: "USD",
    status: "completed",
    deliveryDate: "2026-06-12",
    deliveryLocation: "Bethlehem, Palestine",
    createdAt: "2026-06-01",
    payment: {
      id: "payment-5",
      dealId: "deal-5",
      amount: 10300,
      currency: "USD",
      status: "released",
      escrowReference: "ESC-2026-005",
      createdAt: "2026-06-01",
      releasedAt: "2026-06-13",
    },
  },
  {
    id: "deal-6",
    listingId: "listing-3",
    farmerId: "farmer-3",
    buyerId: "buyer-3",
    title: "Strawberry retail crates",
    quantity: 260,
    unit: "crate",
    unitPrice: 8.5,
    totalValue: 2210,
    currency: "USD",
    status: "disputed",
    deliveryDate: "2026-06-15",
    deliveryLocation: "Jerusalem, Palestine",
    createdAt: "2026-06-07",
    payment: {
      id: "payment-6",
      dealId: "deal-6",
      amount: 2210,
      currency: "USD",
      status: "escrow_funded",
      escrowReference: "ESC-2026-006",
      createdAt: "2026-06-07",
    },
  },
];

export const inspections: Inspection[] = [
  {
    id: "inspection-1",
    dealId: "deal-1",
    officerId: "officer-1",
    listingId: "listing-1",
    crop: "Tomatoes",
    location: "Jenin, Palestine",
    scheduledDate: "2026-06-21",
    status: "assigned",
  },
  {
    id: "inspection-2",
    dealId: "deal-2",
    officerId: "officer-2",
    listingId: "listing-4",
    crop: "Medjool dates",
    location: "Jericho, Palestine",
    scheduledDate: "2026-06-27",
    status: "scheduled",
  },
  {
    id: "inspection-3",
    dealId: "deal-3",
    officerId: "officer-1",
    listingId: "listing-2",
    crop: "Olive oil",
    location: "Nablus, Palestine",
    scheduledDate: "2026-06-16",
    status: "submitted",
    report: {
      id: "report-1",
      inspectionId: "inspection-3",
      grade: "A",
      moisturePercent: 0.2,
      defectRatePercent: 1.1,
      packagingNotes: "Tins sealed correctly and labels match batch records.",
      summary: "Batch meets the requested commercial quality standard.",
      submittedAt: "2026-06-16",
      approved: true,
    },
  },
  {
    id: "inspection-4",
    dealId: "deal-6",
    officerId: "officer-2",
    listingId: "listing-3",
    crop: "Strawberries",
    location: "Tulkarm, Palestine",
    scheduledDate: "2026-06-15",
    status: "rejected",
    report: {
      id: "report-2",
      inspectionId: "inspection-4",
      grade: "C",
      defectRatePercent: 9.8,
      packagingNotes: "Several crates arrived warm and damaged.",
      summary: "Shipment does not match the accepted grade specification.",
      submittedAt: "2026-06-15",
      approved: false,
    },
  },
];

export const disputes: Dispute[] = [
  {
    id: "dispute-1",
    dealId: "deal-6",
    openedByUserId: "buyer-3",
    reason: "Delivered strawberries had a higher defect rate than agreed.",
    status: "under_review",
    priority: "high",
    createdAt: "2026-06-15",
  },
  {
    id: "dispute-2",
    dealId: "deal-3",
    openedByUserId: "farmer-2",
    reason: "Buyer requested a delayed delivery window after escrow funding.",
    status: "open",
    priority: "medium",
    createdAt: "2026-06-14",
  },
  {
    id: "dispute-3",
    dealId: "deal-5",
    openedByUserId: "buyer-2",
    reason: "Clarification requested on final released payment fees.",
    status: "resolved",
    priority: "low",
    createdAt: "2026-06-12",
  },
];

export const reviews: Review[] = [
  {
    id: "review-1",
    dealId: "deal-5",
    reviewerId: "buyer-2",
    revieweeId: "farmer-4",
    rating: 4,
    comment: "Responsive seller and clear packaging records.",
    createdAt: "2026-06-13",
  },
  {
    id: "review-2",
    dealId: "deal-5",
    reviewerId: "farmer-4",
    revieweeId: "buyer-2",
    rating: 5,
    comment: "Payment was released on time after delivery confirmation.",
    createdAt: "2026-06-13",
  },
];

export const adminStats: AdminDashboardStats = {
  activeUsers: users.filter((user) => user.status === "active").length,
  activeListings: listings.filter((listing) => listing.status === "active").length,
  openRFQs: rfqs.filter((rfq) => rfq.status === "open").length,
  escrowBalance: deals
    .filter((deal) => deal.payment.status === "escrow_funded")
    .reduce((total, deal) => total + deal.payment.amount, 0),
  monthlyRevenue: 8420,
  pendingInspections: inspections.filter(
    (inspection) => inspection.status === "assigned" || inspection.status === "scheduled",
  ).length,
  openDisputes: disputes.filter((dispute) => dispute.status !== "resolved").length,
};

export type FarmerListingStatus = "Active" | "Expired" | "Draft";

export type FarmerListingItem = {
  id: string;
  name: string;
  status: FarmerListingStatus;
  price: string;
  currency: string;
  unit: string;
  quantity: string;
  views: number;
  rfqsReceived: number;
  image: string;
};

export const farmerListingStats = [
  { label: "Total Listings", value: "12", icon: "total" },
  { label: "Active Listings", value: "8", icon: "active" },
  { label: "Expiring Soon", value: "2", icon: "expiring" },
  { label: "Total Views", value: "234", icon: "views" },
];

export const farmerListingItems: FarmerListingItem[] = [
  {
    id: "fresh-tomatoes",
    name: "Fresh Tomatoes",
    status: "Active",
    price: "28.00",
    currency: "SAR",
    unit: "kg",
    quantity: "1,000 kg",
    views: 234,
    rfqsReceived: 5,
    image: "/images/farmer/listings/tomatoes-listing.jpg",
  },
  {
    id: "green-olives",
    name: "Green Olives",
    status: "Active",
    price: "95.00",
    currency: "SAR",
    unit: "kg",
    quantity: "500 kg",
    views: 234,
    rfqsReceived: 5,
    image: "/images/farmer/listings/green-olives-listing.jpg",
  },
  {
    id: "premium-wheat",
    name: "Wheat (Premium)",
    status: "Expired",
    price: "22.00",
    currency: "SAR",
    unit: "kg",
    quantity: "2,000 kg",
    views: 234,
    rfqsReceived: 5,
    image: "/images/farmer/listings/wheat-listing.jpg",
  },
  {
    id: "organic-cucumbers",
    name: "Organic Cucumbers",
    status: "Active",
    price: "18.00",
    currency: "SAR",
    unit: "kg",
    quantity: "850 kg",
    views: 188,
    rfqsReceived: 4,
    image: "/images/farmer/listings/tomatoes-listing.jpg",
  },
  {
    id: "olive-oil-batch",
    name: "Olive Oil Batch",
    status: "Draft",
    price: "42.00",
    currency: "SAR",
    unit: "liter",
    quantity: "300 liters",
    views: 96,
    rfqsReceived: 2,
    image: "/images/farmer/listings/green-olives-listing.jpg",
  },
  {
    id: "durum-wheat",
    name: "Durum Wheat",
    status: "Active",
    price: "25.00",
    currency: "SAR",
    unit: "kg",
    quantity: "1,600 kg",
    views: 211,
    rfqsReceived: 6,
    image: "/images/farmer/listings/wheat-listing.jpg",
  },
  {
    id: "cherry-tomatoes",
    name: "Cherry Tomatoes",
    status: "Active",
    price: "34.00",
    currency: "SAR",
    unit: "kg",
    quantity: "420 kg",
    views: 172,
    rfqsReceived: 3,
    image: "/images/farmer/listings/tomatoes-listing.jpg",
  },
  {
    id: "green-olive-crates",
    name: "Green Olive Crates",
    status: "Expired",
    price: "88.00",
    currency: "SAR",
    unit: "kg",
    quantity: "650 kg",
    views: 143,
    rfqsReceived: 2,
    image: "/images/farmer/listings/green-olives-listing.jpg",
  },
  {
    id: "wheat-flour-grade-a",
    name: "Wheat Flour Grade A",
    status: "Active",
    price: "31.00",
    currency: "SAR",
    unit: "kg",
    quantity: "900 kg",
    views: 207,
    rfqsReceived: 5,
    image: "/images/farmer/listings/wheat-listing.jpg",
  },
  {
    id: "tomato-bulk-pack",
    name: "Tomato Bulk Pack",
    status: "Draft",
    price: "24.00",
    currency: "SAR",
    unit: "kg",
    quantity: "1,200 kg",
    views: 84,
    rfqsReceived: 1,
    image: "/images/farmer/listings/tomatoes-listing.jpg",
  },
  {
    id: "picked-olives",
    name: "Picked Olives",
    status: "Active",
    price: "72.00",
    currency: "SAR",
    unit: "kg",
    quantity: "760 kg",
    views: 195,
    rfqsReceived: 4,
    image: "/images/farmer/listings/green-olives-listing.jpg",
  },
  {
    id: "harvest-wheat",
    name: "Harvest Wheat",
    status: "Active",
    price: "20.00",
    currency: "SAR",
    unit: "kg",
    quantity: "2,400 kg",
    views: 221,
    rfqsReceived: 7,
    image: "/images/farmer/listings/wheat-listing.jpg",
  },
];

export type FarmerDealStatus = "Active" | "Pending" | "Completed" | "Disputed" | "Cancelled";

export type FarmerDealItem = {
  id: string;
  product: string;
  quantity?: string;
  buyer: string;
  status: FarmerDealStatus;
  amount: string;
  currency: string;
  date: string;
  image: string;
};

export const farmerDealStats = [
  { label: "Active Deals", value: "5", icon: "active", tone: "green" },
  { label: "Pending Payment", value: "2", icon: "payment", tone: "yellow" },
  { label: "Completed", value: "156", icon: "completed", tone: "slate" },
  { label: "Total Value", value: "89,000", suffix: "SAR", icon: "value", tone: "green" },
];

export const farmerDeals: FarmerDealItem[] = [
  {
    id: "DEAL-1042",
    product: "Tomatoes",
    quantity: "500kg",
    buyer: "Green Kitchen",
    status: "Active",
    amount: "7,000",
    currency: "SAR",
    date: "March 2025",
    image: "/images/farmer/listings/tomatoes-listing.jpg",
  },
  {
    id: "DEAL-1038",
    product: "Olives",
    quantity: "200kg",
    buyer: "Food Factory",
    status: "Completed",
    amount: "4,500",
    currency: "SAR",
    date: "March 2025",
    image: "/images/farmer/listings/green-olives-listing.jpg",
  },
  {
    id: "DEAL-1035",
    product: "Wheat",
    buyer: "Pending Inspection",
    status: "Pending",
    amount: "12,000",
    currency: "SAR",
    date: "March 2025",
    image: "/images/farmer/listings/wheat-listing.jpg",
  },
  {
    id: "DEAL-1030",
    product: "Tomatoes",
    buyer: "Fresh Mart",
    status: "Disputed",
    amount: "7,000",
    currency: "SAR",
    date: "March 2025",
    image: "/images/farmer/listings/tomatoes-listing.jpg",
  },
  {
    id: "DEAL-1028",
    product: "Green Olives",
    quantity: "350kg",
    buyer: "Al Madinah Mills",
    status: "Active",
    amount: "9,800",
    currency: "SAR",
    date: "February 2025",
    image: "/images/farmer/listings/green-olives-listing.jpg",
  },
  {
    id: "DEAL-1025",
    product: "Wheat",
    quantity: "1,200kg",
    buyer: "Saudi Fresh Ltd.",
    status: "Pending",
    amount: "15,500",
    currency: "SAR",
    date: "February 2025",
    image: "/images/farmer/listings/wheat-listing.jpg",
  },
  {
    id: "DEAL-1021",
    product: "Tomatoes",
    quantity: "750kg",
    buyer: "Daily Fresh",
    status: "Active",
    amount: "8,200",
    currency: "SAR",
    date: "January 2025",
    image: "/images/farmer/listings/tomatoes-listing.jpg",
  },
  {
    id: "DEAL-1018",
    product: "Olives",
    buyer: "Gulf Traders",
    status: "Cancelled",
    amount: "3,900",
    currency: "SAR",
    date: "January 2025",
    image: "/images/farmer/listings/green-olives-listing.jpg",
  },
  {
    id: "DEAL-1015",
    product: "Wheat",
    quantity: "900kg",
    buyer: "Healthy Basket",
    status: "Completed",
    amount: "11,400",
    currency: "SAR",
    date: "December 2024",
    image: "/images/farmer/listings/wheat-listing.jpg",
  },
  {
    id: "DEAL-1012",
    product: "Tomatoes",
    quantity: "400kg",
    buyer: "Urban Plate",
    status: "Active",
    amount: "5,600",
    currency: "SAR",
    date: "December 2024",
    image: "/images/farmer/listings/tomatoes-listing.jpg",
  },
  {
    id: "DEAL-1009",
    product: "Olives",
    quantity: "280kg",
    buyer: "Golden Foods",
    status: "Active",
    amount: "6,300",
    currency: "SAR",
    date: "November 2024",
    image: "/images/farmer/listings/green-olives-listing.jpg",
  },
  {
    id: "DEAL-1005",
    product: "Wheat",
    quantity: "2,000kg",
    buyer: "Levant Wholesale",
    status: "Completed",
    amount: "18,000",
    currency: "SAR",
    date: "November 2024",
    image: "/images/farmer/listings/wheat-listing.jpg",
  },
];
