import type { QualityOfficerAssignment } from "@/components/dashboard/quality-officer/assignments/quality-officer-assignments.types";

export const qualityOfficerAssignments: QualityOfficerAssignment[] = [
  {
    id: "assignment-1542",
    dealId: "#D-2025-1542",
    productName: "Tomatoes",
    category: "Fresh Vegetables",
    productImage: "/images/farmer/listings/tomatoes-listing.jpg",
    farmName: "Al Sa'adah Farm",
    location: "Al Ahsa, Saudi Arabia",
    buyer: "Green Fields Trading Co.",
    requiredDate: "May 26, 2025",
    requiredTime: "09:00 AM",
    urgencyLabel: "2 days left",
    assignedDate: "May 24, 2025",
    assignedTime: "10:15 AM",
    status: "pending",
  },
  {
    id: "assignment-1531",
    dealId: "#D-2025-1531",
    productName: "Potatoes",
    category: "Root Vegetables",
    productImage: "/images/farmer/create-listing/placeholders/listing-photo-placeholder-4.jpg",
    farmName: "Golden Harvest Farm",
    location: "Al Kharj, Saudi Arabia",
    buyer: "Desert Foods Company",
    requiredDate: "May 23, 2025",
    requiredTime: "10:00 AM",
    assignedDate: "May 22, 2025",
    assignedTime: "09:20 AM",
    status: "in-progress",
  },
  {
    id: "assignment-1519",
    dealId: "#D-2025-1519",
    productName: "Onions",
    category: "Vegetables",
    productImage: "/images/farmer/create-listing/placeholders/listing-photo-placeholder-6.jpg",
    farmName: "Al Marai Farm",
    location: "Qassim, Saudi Arabia",
    buyer: "Global Produce Market",
    requiredDate: "May 21, 2025",
    requiredTime: "09:00 AM",
    assignedDate: "May 20, 2025",
    assignedTime: "08:10 AM",
    status: "completed",
  },
  {
    id: "assignment-1508",
    dealId: "#D-2025-1508",
    productName: "Strawberries",
    category: "Fruits",
    productImage: "/images/farmer/create-listing/placeholders/listing-photo-placeholder-8.jpg",
    farmName: "Berry Land Farm",
    location: "Taif, Saudi Arabia",
    buyer: "Premium Fruits Co.",
    requiredDate: "May 20, 2025",
    requiredTime: "09:00 AM",
    urgencyLabel: "1 day overdue",
    assignedDate: "May 19, 2025",
    assignedTime: "10:05 AM",
    status: "overdue",
  },
];

export const assignmentStatusCounts = {
  all: 24,
  pending: 8,
  "in-progress": 6,
  completed: 10,
  overdue: 2,
} as const;
