import type { BuyerReview, BuyerReviewsStats } from "@/components/dashboard/buyer/reviews/buyer-reviews.types";

export const buyerReviewsStats: BuyerReviewsStats = {
  averageRatingGiven: 4.8,
  totalSubmitted: 124,
  awaitingFeedback: 8,
  sentiment: {
    fiveStar: 75,
    fourStar: 15,
    threeStar: 7,
    others: 3,
  },
};

export const buyerReviews: BuyerReview[] = [
  {
    id: "review-001",
    supplierName: "Midwest Grain Masters",
    supplierSubtitle: "Verified Supplier",
    supplierInitials: "MG",
    productCategory: "Organic Wheat",
    productSubcategory: "Bulk",
    rating: 5,
    reviewDate: "Oct 24, 2023",
    status: "published",
  },
  {
    id: "review-002",
    supplierName: "AgriPlus Fertilizer",
    supplierSubtitle: "Premium Partner",
    supplierInitials: "AF",
    productCategory: "NPK 10-26-26",
    rating: 4,
    reviewDate: "Oct 12, 2023",
    status: "published",
  },
  {
    id: "review-003",
    supplierName: "Eco-Sustain Solutions",
    supplierSubtitle: "New Supplier",
    supplierInitials: "ES",
    productCategory: "Drip Irrigation",
    productSubcategory: "Parts",
    rating: null,
    reviewDate: null,
    status: "draft",
  },
  {
    id: "review-004",
    supplierName: "Harvest Route Logistics",
    supplierSubtitle: "Delivery Partner",
    supplierInitials: "HR",
    productCategory: "Logistics",
    productSubcategory: "Cold Chain",
    rating: 5,
    reviewDate: "Sep 30, 2023",
    status: "published",
  },
  {
    id: "review-005",
    supplierName: "GreenPack Arabia",
    supplierSubtitle: "Packaging Vendor",
    supplierInitials: "GP",
    productCategory: "Packaging",
    productSubcategory: "Crates",
    rating: 4,
    reviewDate: "Sep 22, 2023",
    status: "published",
  },
  {
    id: "review-006",
    supplierName: "Oasis Irrigation Works",
    supplierSubtitle: "Verified Supplier",
    supplierInitials: "OI",
    productCategory: "Irrigation",
    productSubcategory: "Valves",
    rating: null,
    reviewDate: "Pending",
    status: "pending",
  },
  {
    id: "review-007",
    supplierName: "Golden Fields Co.",
    supplierSubtitle: "Market Elite",
    supplierInitials: "GF",
    productCategory: "Organic Wheat",
    productSubcategory: "Bulk",
    rating: 5,
    reviewDate: "Sep 14, 2023",
    status: "published",
  },
  {
    id: "review-008",
    supplierName: "Fresh Inputs Trading",
    supplierSubtitle: "Premium Partner",
    supplierInitials: "FI",
    productCategory: "Fertilizer",
    productSubcategory: "Organic Blend",
    rating: 3,
    reviewDate: "Aug 28, 2023",
    status: "published",
  },
  {
    id: "review-009",
    supplierName: "Saudi Hydro Systems",
    supplierSubtitle: "New Supplier",
    supplierInitials: "SH",
    productCategory: "Irrigation",
    productSubcategory: "Pumps",
    rating: null,
    reviewDate: null,
    status: "draft",
  },
  {
    id: "review-010",
    supplierName: "Palm Grove Packaging",
    supplierSubtitle: "Verified Supplier",
    supplierInitials: "PG",
    productCategory: "Packaging",
    productSubcategory: "Cartons",
    rating: 5,
    reviewDate: "Aug 16, 2023",
    status: "published",
  },
];
