import type { AdminDispute } from "@/components/dashboard/admin/disputes/admin-disputes.types";

const sharedEvidence = [
  {
    date: "May 24, 2025",
    fileName: "tomatoes_field_01.jpg",
    fileType: "image",
    id: "evidence-1",
    image: "/images/farmer/listings/tomatoes-listing.jpg",
    source: "Farmer",
    time: "08:45 AM",
  },
  {
    date: "May 24, 2025",
    fileName: "received_tomatoes.jpg",
    fileType: "image",
    id: "evidence-2",
    image: "/images/marketplace/tomatoes.jpg",
    source: "Buyer",
    time: "09:10 AM",
  },
  {
    date: "May 24, 2025",
    fileName: "packing_list.pdf",
    fileType: "pdf",
    id: "evidence-3",
    image: "/images/farmer/create-listing/placeholders/listing-photo-placeholder-3.jpg",
    source: "Farmer",
    time: "09:20 AM",
  },
  {
    date: "May 24, 2025",
    fileName: "quality_claim_report.pdf",
    fileType: "pdf",
    id: "evidence-4",
    image: "/images/farmer/create-listing/placeholders/listing-photo-placeholder-4.jpg",
    source: "Buyer",
    time: "09:35 AM",
  },
  {
    date: "May 24, 2025",
    fileName: "field_condition_note.pdf",
    fileType: "pdf",
    id: "evidence-5",
    image: "/images/farmer/create-listing/placeholders/listing-photo-placeholder-5.jpg",
    source: "Farmer",
    time: "10:05 AM",
  },
] satisfies AdminDispute["evidence"];

const sharedInspectionReport = {
  inspectionDate: "May 23, 2025",
  inspector: "Ahmed Khalid",
  overallGrade: "B",
  reportId: "#IR-2025-1542",
  status: "completed",
} satisfies AdminDispute["inspectionReport"];

const sharedCommunicationLog = [
  {
    date: "May 24, 2025",
    id: "message-1",
    message: "The received tomatoes do not meet the agreed quality standards.",
    role: "Buyer",
    sender: "Buyer (Green Fields Co.)",
    time: "09:15 AM",
  },
  {
    date: "May 24, 2025",
    id: "message-2",
    message: "We believe the quality was acceptable at the time of harvest.",
    role: "Farmer",
    sender: "Farmer (Abdullah Al Mutairi)",
    time: "09:47 AM",
  },
  {
    date: "May 24, 2025",
    id: "message-3",
    message: "Please provide additional evidence to support your claims.",
    role: "Admin",
    sender: "Admin",
    time: "10:20 AM",
  },
] satisfies AdminDispute["communicationLog"];

export const adminDisputes: AdminDispute[] = [
  {
    amountInDispute: 25000,
    buyer: "Green Fields Trading Co.",
    dealId: "#D-2025-1542",
    disputeId: "#D-2025-1542",
    evidence: sharedEvidence,
    farmer: "Abdullah Al Mutairi",
    id: "admin-dispute-1542",
    inspectionReport: sharedInspectionReport,
    communicationLog: sharedCommunicationLog,
    dealValue: 25000,
    openedAge: "1 day, 4 hours ago",
    openedAt: "May 24, 2025 at 09:15 AM",
    openedByName: "Green Fields Trading Co.",
    openedByRole: "Buyer",
    openedDate: "May 24, 2025",
    paymentStatus: "frozen",
    product: "Tomatoes",
    status: "open",
  },
  {
    amountInDispute: 18000,
    buyer: "Green Fields Trading Co.",
    dealId: "#D-2025-1538",
    disputeId: "#D-2025-1538",
    evidence: sharedEvidence,
    farmer: "Abdullah Al Mutairi",
    id: "admin-dispute-1538",
    inspectionReport: sharedInspectionReport,
    communicationLog: sharedCommunicationLog,
    dealValue: 18000,
    openedAge: "2 days, 6 hours ago",
    openedAt: "May 23, 2025 at 11:20 AM",
    openedByName: "Abdullah Al Mutairi",
    openedByRole: "Farmer",
    openedDate: "May 23, 2025",
    paymentStatus: "frozen",
    product: "Tomatoes",
    status: "under-review",
  },
  {
    amountInDispute: 31500,
    buyer: "Al Noor Foods",
    dealId: "#D-2025-1529",
    disputeId: "#D-2025-1529",
    evidence: sharedEvidence,
    farmer: "Abdullah Al Mutairi",
    id: "admin-dispute-1529",
    inspectionReport: sharedInspectionReport,
    communicationLog: sharedCommunicationLog,
    dealValue: 31500,
    openedAge: "3 days, 2 hours ago",
    openedAt: "May 22, 2025 at 08:10 AM",
    openedByName: "Al Noor Foods",
    openedByRole: "Buyer",
    openedDate: "May 22, 2025",
    paymentStatus: "frozen",
    product: "Tomatoes",
    status: "open",
  },
  {
    amountInDispute: 12750,
    buyer: "Faisal Al Qahtani",
    dealId: "#D-2025-1517",
    disputeId: "#D-2025-1517",
    evidence: sharedEvidence,
    farmer: "Faisal Al Qahtani",
    id: "admin-dispute-1517",
    inspectionReport: sharedInspectionReport,
    communicationLog: sharedCommunicationLog,
    dealValue: 12750,
    openedAge: "7 days ago",
    openedAt: "May 18, 2025 at 01:40 PM",
    openedByName: "Faisal Al Qahtani",
    openedByRole: "Farmer",
    openedDate: "May 18, 2025",
    paymentStatus: "released",
    product: "Tomatoes",
    status: "resolved",
  },
  {
    amountInDispute: 22000,
    buyer: "Organic World Co.",
    dealId: "#D-2025-1503",
    disputeId: "#D-2025-1503",
    evidence: sharedEvidence,
    farmer: "Abdullah Al Mutairi",
    id: "admin-dispute-1503",
    inspectionReport: sharedInspectionReport,
    communicationLog: sharedCommunicationLog,
    dealValue: 22000,
    openedAge: "8 days ago",
    openedAt: "May 17, 2025 at 04:55 PM",
    openedByName: "Organic World Co.",
    openedByRole: "Buyer",
    openedDate: "May 17, 2025",
    paymentStatus: "released",
    product: "Tomatoes",
    status: "resolved",
  },
  {
    amountInDispute: 15300,
    buyer: "Salem Al Harbi",
    dealId: "#D-2025-1498",
    disputeId: "#D-2025-1498",
    evidence: sharedEvidence,
    farmer: "Salem Al Harbi",
    id: "admin-dispute-1498",
    inspectionReport: sharedInspectionReport,
    communicationLog: sharedCommunicationLog,
    dealValue: 15300,
    openedAge: "9 days ago",
    openedAt: "May 16, 2025 at 12:15 PM",
    openedByName: "Salem Al Harbi",
    openedByRole: "Farmer",
    openedDate: "May 16, 2025",
    paymentStatus: "frozen",
    product: "Tomatoes",
    status: "under-review",
  },
];
