export type PaymentStatus = "In Escrow" | "Released" | "Withdrawn" | "Refunded" | "Failed";

export type PaymentStatusFilter = "All" | PaymentStatus;

export type PaymentTransaction = {
  id: string;
  transactionId: string;
  contractId: string;
  buyer: string;
  buyerInitials: string;
  type: string;
  amount: number;
  amountDirection: "positive" | "negative" | "neutral";
  status: PaymentStatus;
  date: string;
  dateValue: string;
};

export const paymentStats = [
  {
    label: "Available Balance",
    value: "SAR 12,450",
    note: "Ready to withdraw",
    icon: "wallet",
    tone: "green",
  },
  {
    label: "Pending in Escrow",
    value: "SAR 34,200",
    note: "Across 6 active contracts",
    icon: "shield",
    tone: "yellow",
  },
  {
    label: "Total Received (Lifetime)",
    value: "SAR 186,000",
    note: "↑ SAR 15,000 this month",
    icon: "trend",
    tone: "green",
  },
  {
    label: "Withdrawn This Month",
    value: "SAR 8,000",
    note: "Last withdrawal: Jun 18",
    icon: "bank",
    tone: "slate",
  },
];

export const paymentTabs: Array<{ label: PaymentStatusFilter; count: number }> = [
  { label: "All", count: 124 },
  { label: "In Escrow", count: 6 },
  { label: "Released", count: 98 },
  { label: "Withdrawn", count: 14 },
  { label: "Refunded", count: 2 },
  { label: "Failed", count: 1 },
];

export const paymentTransactions: PaymentTransaction[] = [
  {
    id: "txn-0456",
    transactionId: "#TXN-2025-0456",
    contractId: "#CTR-2025-104",
    buyer: "GreenHarvest Ltd.",
    buyerInitials: "GH",
    type: "Escrow Funded",
    amount: 12400,
    amountDirection: "neutral",
    status: "In Escrow",
    date: "Jun 24, 2025",
    dateValue: "2025-06-24",
  },
  {
    id: "txn-0455",
    transactionId: "#TXN-2025-0455",
    contractId: "#CTR-2025-098",
    buyer: "Oasis Fruits",
    buyerInitials: "OF",
    type: "Release to Wallet",
    amount: 8250,
    amountDirection: "positive",
    status: "Released",
    date: "Jun 22, 2025",
    dateValue: "2025-06-22",
  },
  {
    id: "txn-0450",
    transactionId: "#TXN-2025-0450",
    contractId: "-",
    buyer: "Withdrawal (Bank)",
    buyerInitials: "BANK",
    type: "Payout",
    amount: -5000,
    amountDirection: "negative",
    status: "Withdrawn",
    date: "Jun 18, 2025",
    dateValue: "2025-06-18",
  },
  {
    id: "txn-0442",
    transactionId: "#TXN-2025-0442",
    contractId: "#CTR-2025-085",
    buyer: "Negev Tech",
    buyerInitials: "NT",
    type: "Service Refund",
    amount: 1200,
    amountDirection: "neutral",
    status: "Refunded",
    date: "Jun 15, 2025",
    dateValue: "2025-06-15",
  },
  {
    id: "txn-0431",
    transactionId: "#TXN-2025-0431",
    contractId: "#CTR-2025-072",
    buyer: "Urban Distribution",
    buyerInitials: "UD",
    type: "Escrow Funding",
    amount: 15000,
    amountDirection: "negative",
    status: "Failed",
    date: "Jun 12, 2025",
    dateValue: "2025-06-12",
  },
  {
    id: "txn-0428",
    transactionId: "#TXN-2025-0428",
    contractId: "#CTR-2025-068",
    buyer: "Fresh Mart",
    buyerInitials: "FM",
    type: "Release to Wallet",
    amount: 6200,
    amountDirection: "positive",
    status: "Released",
    date: "Jun 9, 2025",
    dateValue: "2025-06-09",
  },
  {
    id: "txn-0425",
    transactionId: "#TXN-2025-0425",
    contractId: "#CTR-2025-063",
    buyer: "Green Kitchen Restaurant",
    buyerInitials: "GK",
    type: "Escrow Funded",
    amount: 9800,
    amountDirection: "neutral",
    status: "In Escrow",
    date: "Jun 5, 2025",
    dateValue: "2025-06-05",
  },
  {
    id: "txn-0419",
    transactionId: "#TXN-2025-0419",
    contractId: "-",
    buyer: "Withdrawal (Bank)",
    buyerInitials: "BANK",
    type: "Payout",
    amount: -3000,
    amountDirection: "negative",
    status: "Withdrawn",
    date: "May 30, 2025",
    dateValue: "2025-05-30",
  },
  {
    id: "txn-0415",
    transactionId: "#TXN-2025-0415",
    contractId: "#CTR-2025-059",
    buyer: "Food Factory",
    buyerInitials: "FF",
    type: "Release to Wallet",
    amount: 4500,
    amountDirection: "positive",
    status: "Released",
    date: "May 28, 2025",
    dateValue: "2025-05-28",
  },
  {
    id: "txn-0410",
    transactionId: "#TXN-2025-0410",
    contractId: "#CTR-2025-055",
    buyer: "Al Madinah Mills",
    buyerInitials: "AM",
    type: "Escrow Funded",
    amount: 18200,
    amountDirection: "neutral",
    status: "In Escrow",
    date: "May 24, 2025",
    dateValue: "2025-05-24",
  },
  {
    id: "txn-0406",
    transactionId: "#TXN-2025-0406",
    contractId: "#CTR-2025-051",
    buyer: "Saudi Fresh Ltd.",
    buyerInitials: "SF",
    type: "Release to Wallet",
    amount: 7300,
    amountDirection: "positive",
    status: "Released",
    date: "May 20, 2025",
    dateValue: "2025-05-20",
  },
  {
    id: "txn-0402",
    transactionId: "#TXN-2025-0402",
    contractId: "#CTR-2025-047",
    buyer: "Daily Fresh",
    buyerInitials: "DF",
    type: "Service Refund",
    amount: 900,
    amountDirection: "neutral",
    status: "Refunded",
    date: "May 16, 2025",
    dateValue: "2025-05-16",
  },
  {
    id: "txn-0398",
    transactionId: "#TXN-2025-0398",
    contractId: "-",
    buyer: "Withdrawal (Bank)",
    buyerInitials: "BANK",
    type: "Payout",
    amount: -5000,
    amountDirection: "negative",
    status: "Withdrawn",
    date: "May 12, 2025",
    dateValue: "2025-05-12",
  },
  {
    id: "txn-0394",
    transactionId: "#TXN-2025-0394",
    contractId: "#CTR-2025-040",
    buyer: "Gulf Traders",
    buyerInitials: "GT",
    type: "Escrow Funding",
    amount: 6100,
    amountDirection: "negative",
    status: "Failed",
    date: "May 8, 2025",
    dateValue: "2025-05-08",
  },
  {
    id: "txn-0391",
    transactionId: "#TXN-2025-0391",
    contractId: "#CTR-2025-037",
    buyer: "Healthy Basket",
    buyerInitials: "HB",
    type: "Release to Wallet",
    amount: 11200,
    amountDirection: "positive",
    status: "Released",
    date: "May 3, 2025",
    dateValue: "2025-05-03",
  },
];
