import type { BuyerDeal } from "@/components/dashboard/buyer/deals/buyer-deals.types";

const tomatoImage = "/images/farmer/listings/tomatoes-listing.jpg";
const wheatImage = "/images/farmer/listings/wheat-listing.jpg";
const olivesImage = "/images/farmer/listings/green-olives-listing.jpg";
const fallbackProductImage = "/images/farmer/create-listing/placeholders/listing-photo-placeholder-1.jpg";
const farmerAvatar = "/images/farmer/profile/farmer-avatar.jpg";

export const buyerDeals: BuyerDeal[] = [
  {
    amount: 7000,
    deliveryDate: "Mar 20, 2025",
    farmerAvatar,
    farmerName: "Green Kitchen",
    farmerRating: 4.8,
    id: "DEAL-2042",
    productDetail: "500kg",
    productImage: tomatoImage,
    productName: "Tomatoes",
    quantity: "500 kg",
    status: "active",
  },
  {
    amount: 4500,
    deliveryDate: "Mar 22, 2025",
    farmerAvatar,
    farmerName: "Food Factory",
    farmerRating: 4.6,
    id: "DEAL-2038",
    productDetail: "200kg",
    productImage: olivesImage,
    productName: "Olives",
    quantity: "200 kg",
    status: "awaiting",
  },
  {
    amount: 12000,
    deliveryDate: "Mar 25, 2025",
    farmerAvatar,
    farmerName: "Golden Fields",
    farmerRating: 4.7,
    id: "DEAL-2035",
    productDetail: "1,000kg",
    productImage: wheatImage,
    productName: "Wheat",
    quantity: "1,000 kg",
    status: "active",
  },
  {
    amount: 7000,
    deliveryDate: "Mar 10, 2025",
    farmerAvatar,
    farmerName: "Fresh Mart",
    farmerRating: 4.5,
    id: "DEAL-2030",
    productDetail: "500kg",
    productImage: tomatoImage,
    productName: "Tomatoes",
    quantity: "500 kg",
    status: "completed",
  },
  {
    amount: 3600,
    deliveryDate: "Mar 28, 2025",
    farmerAvatar,
    farmerName: "Green Kitchen",
    farmerRating: 4.8,
    id: "DEAL-2029",
    productDetail: "300kg",
    productImage: fallbackProductImage,
    productName: "Lettuce",
    quantity: "300 kg",
    status: "active",
  },
  {
    amount: 5800,
    deliveryDate: "Apr 02, 2025",
    farmerAvatar,
    farmerName: "Food Factory",
    farmerRating: 4.6,
    id: "DEAL-2028",
    productDetail: "240kg",
    productImage: olivesImage,
    productName: "Olives",
    quantity: "240 kg",
    status: "cancelled",
  },
  {
    amount: 9200,
    deliveryDate: "Apr 04, 2025",
    farmerAvatar,
    farmerName: "Golden Fields",
    farmerRating: 4.7,
    id: "DEAL-2027",
    productDetail: "800kg",
    productImage: wheatImage,
    productName: "Wheat",
    quantity: "800 kg",
    status: "awaiting",
  },
  {
    amount: 4200,
    deliveryDate: "Apr 06, 2025",
    farmerAvatar,
    farmerName: "Fresh Mart",
    farmerRating: 4.5,
    id: "DEAL-2026",
    productDetail: "350kg",
    productImage: tomatoImage,
    productName: "Tomatoes",
    quantity: "350 kg",
    status: "refunded",
  },
  {
    amount: 6300,
    deliveryDate: "Apr 08, 2025",
    farmerAvatar,
    farmerName: "Green Kitchen",
    farmerRating: 4.8,
    id: "DEAL-2025",
    productDetail: "450kg",
    productImage: fallbackProductImage,
    productName: "Cucumbers",
    quantity: "450 kg",
    status: "active",
  },
  {
    amount: 4900,
    deliveryDate: "Apr 12, 2025",
    farmerAvatar,
    farmerName: "Food Factory",
    farmerRating: 4.6,
    id: "DEAL-2024",
    productDetail: "210kg",
    productImage: olivesImage,
    productName: "Olives",
    quantity: "210 kg",
    status: "completed",
  },
  {
    amount: 11000,
    deliveryDate: "Apr 14, 2025",
    farmerAvatar,
    farmerName: "Golden Fields",
    farmerRating: 4.7,
    id: "DEAL-2023",
    productDetail: "950kg",
    productImage: wheatImage,
    productName: "Wheat",
    quantity: "950 kg",
    status: "completed",
  },
  {
    amount: 5400,
    deliveryDate: "Apr 18, 2025",
    farmerAvatar,
    farmerName: "Fresh Mart",
    farmerRating: 4.5,
    id: "DEAL-2022",
    productDetail: "400kg",
    productImage: tomatoImage,
    productName: "Tomatoes",
    quantity: "400 kg",
    status: "active",
  },
];

export const buyerDealStats = {
  activeDeals: 4,
  awaitingConfirmation: 2,
  completed: 128,
  totalSpent: 89000,
};
