import type { AdminUser } from "@/components/dashboard/admin/users/admin-users.types";

export const adminUsers: AdminUser[] = [
  {
    activityLabel: "12 Deals",
    activityScore: 62,
    email: "mohammed.hasan@example.com",
    id: "admin-user-1",
    initials: "MH",
    memberSince: "May 24, 2024",
    name: "Mohammed Al Hasan",
    profileSubtitle: "Verified farmer account",
    registrationDate: "May 24, 2024",
    role: "farmer",
    status: "active",
  },
  {
    activityLabel: "28 Deals",
    activityScore: 74,
    email: "contact@greenfield.com",
    id: "admin-user-2",
    initials: "GF",
    memberSince: "May 20, 2024",
    name: "GreenField Imports LLC",
    profileSubtitle: "Buyer organization account",
    registrationDate: "May 20, 2024",
    role: "buyer",
    status: "active",
  },
  {
    activityLabel: "15 Inspections",
    activityScore: 32,
    affiliatedOrganization: "Palestine Quality Lab for Exports",
    contactNumber: "+970 59 222 3344",
    dateOfBirth: "Apr 12, 1991",
    email: "lina.q@example.com",
    fullLegalName: "Dr. Lina Qassem",
    id: "admin-user-3",
    idNumber: "#QO-00845",
    initials: "LQ",
    licenseIdentity: "QO-2024-1187",
    memberSince: "May 18, 2024",
    name: "Dr. Lina Qassem",
    nationality: "Palestinian",
    primarySpecialization: "Post-harvest Quality",
    profileSubtitle: "Expertise in Agricultural Quality Assurance",
    registrationDate: "May 18, 2024",
    role: "quality-officer",
    status: "pending-verification",
    verifiedLocation: "Nablus, PS",
    yearsExperience: "7 years",
  },
];
