import type { AdminListing } from "@/components/dashboard/admin/listings/admin-listings.types";

export const adminListingsTotalCount = 1248;
export const adminFlaggedListingsCount = 18;

export const adminListings: AdminListing[] = [
  {
    category: "Vegetables",
    datePublished: "Jun 28, 2024",
    description: "Fresh, hand-picked tomatoes from our farm. High quality, naturally grown with care. Perfect for salads, cooking, and sauces.",
    farmer: { name: "Omar Hassan", verified: true },
    id: "listing-1",
    listingId: "LIS-2024-0001",
    location: "Jenin, Palestine",
    name: "Fresh Tomatoes",
    price: "$0.85 / kg",
    publishedDateISO: "2024-06-28",
    quantity: "250 kg",
    status: "active",
    timePublished: "10:30 AM",
  },
  {
    category: "Vegetables",
    datePublished: "Jun 28, 2024",
    description: "Clean, firm white potatoes packed for wholesale buyers and local market distribution.",
    farmer: { name: "Ahmed Darwish", verified: true },
    id: "listing-2",
    listingId: "LIS-2024-0002",
    location: "Nablus, Palestine",
    name: "White Potatoes",
    price: "$0.60 / kg",
    publishedDateISO: "2024-06-28",
    quantity: "500 kg",
    status: "pending-review",
    timePublished: "09:15 AM",
  },
  {
    category: "Fruits",
    datePublished: "Jun 27, 2024",
    description: "Bright Valencia oranges selected for juicing, fresh retail, and food-service buyers.",
    farmer: { name: "Sami Abdullah", verified: false },
    id: "listing-3",
    listingId: "LIS-2024-0003",
    location: "Jericho, Palestine",
    name: "Valencia Oranges",
    price: "$0.45 / kg",
    publishedDateISO: "2024-06-27",
    quantity: "1,000 kg",
    status: "flagged",
    timePublished: "04:20 PM",
  },
  {
    category: "Grains",
    datePublished: "Jun 27, 2024",
    description: "Locally harvested wheat grains prepared for milling and bulk agricultural buyers.",
    farmer: { name: "Khaled Nasser", verified: true },
    id: "listing-4",
    listingId: "LIS-2024-0004",
    location: "Hebron, Palestine",
    name: "Wheat Grains",
    price: "$0.35 / kg",
    publishedDateISO: "2024-06-27",
    quantity: "2,000 kg",
    status: "active",
    timePublished: "02:10 PM",
  },
];
