import type {
  BuyerActionRequiredNotification,
  BuyerNotification,
  BuyerNotificationTab,
} from "@/components/dashboard/buyer/notifications/buyer-notifications.types";

export const buyerNotificationTabs: Array<{ label: string; value: BuyerNotificationTab; count?: number }> = [
  { label: "All", value: "all", count: 24 },
  { label: "Unread", value: "unread", count: 7 },
  { label: "Purchases", value: "purchases", count: 8 },
  { label: "Deliveries", value: "deliveries", count: 5 },
  { label: "Payments", value: "payments", count: 10 },
  { label: "Messages", value: "messages", count: 3 },
  { label: "Disputes", value: "disputes", count: 2 },
  { label: "System", value: "system" },
];

export const buyerActionRequiredItems: BuyerActionRequiredNotification[] = [
  {
    id: "confirm-receipt-dl-0456",
    badge: "Confirm Receipt",
    title: "Confirm Delivery: Deal #DL-0456",
    description: "Green Fields Co. has marked the order as delivered. Please confirm receipt to release the payment.",
    timeLabel: "Expires in 16h",
    tone: "red",
    primaryActionLabel: "Confirm Receipt",
    primaryToast: "Receipt confirmation will be connected later.",
    secondaryActionLabel: "View Details",
    secondaryToast: "Deal details will be connected later.",
  },
  {
    id: "inspection-result-dl-0483",
    badge: "Inspection Result",
    title: "Quality Inspection Completed: Deal #DL-0483",
    description: "Quality inspection passed for Tomatoes (Batch T-23). Review the report and approve payment release.",
    timeLabel: "Today, 2:45 PM",
    tone: "green",
    primaryActionLabel: "Review Report",
    primaryToast: "Inspection report will be connected later.",
    secondaryActionLabel: "View Details",
    secondaryToast: "Deal details will be connected later.",
  },
];

export const buyerNotifications: BuyerNotification[] = [
  {
    id: "notification-message-green-fields",
    title: "New Message from Green Fields Co.",
    body: "Your order of tomatoes is scheduled for delivery tomorrow at 10:00 AM.",
    meta: "DEAL #DL-0456 • DELIVERY UPDATE",
    timeLabel: "10:24 AM",
    dateGroup: "today",
    category: "messages",
    unread: true,
    dealId: "DL-0456",
    iconType: "message",
  },
  {
    id: "notification-invoice-generated",
    title: "Invoice Generated: INV-2024-112",
    body: "Invoice for Deal #DL-0448 has been generated. Total Amount: 32,000 SAR",
    timeLabel: "9:15 AM",
    dateGroup: "today",
    category: "payments",
    unread: false,
    dealId: "DL-0448",
    iconType: "invoice",
  },
  {
    id: "notification-review-received",
    title: "Supplier Review Received",
    body: "Great buyer to work with. Clear communication and fast payment.",
    meta: "GREEN FIELDS CO.",
    timeLabel: "Yesterday, 4:50 PM",
    dateGroup: "yesterday",
    category: "purchases",
    unread: true,
    iconType: "review",
  },
  {
    id: "notification-payment-processed",
    title: "Payment Processed: 45,000 SAR",
    body: "Payment for Deal #DL-0447 has been released to Green Fields Co.",
    meta: "DEAL #DL-0447 • TOMATOES • BATCH T-21",
    timeLabel: "Yesterday, 2:10 PM",
    dateGroup: "yesterday",
    category: "payments",
    unread: true,
    dealId: "DL-0447",
    iconType: "payment",
  },
  {
    id: "notification-delivery-scheduled",
    title: "Delivery Scheduled",
    body: "FreshMart LLC confirmed delivery for potatoes on May 26.",
    meta: "DEAL #DL-0444 • POTATOES",
    timeLabel: "Yesterday, 11:20 AM",
    dateGroup: "yesterday",
    category: "deliveries",
    unread: true,
    dealId: "DL-0444",
    iconType: "delivery",
  },
  {
    id: "notification-dispute-response",
    title: "Dispute Response Requested",
    body: "A mediator requested supporting documents for an open delivery dispute.",
    meta: "CASE #DIS-8921",
    timeLabel: "Mon, 8:20 AM",
    dateGroup: "older",
    category: "disputes",
    unread: true,
    iconType: "system",
  },
  {
    id: "notification-payment-reminder",
    title: "Payment Reminder",
    body: "Payment authorization is pending for the completed wheat delivery.",
    meta: "DEAL #DL-0438",
    timeLabel: "Sun, 5:15 PM",
    dateGroup: "older",
    category: "payments",
    unread: true,
    dealId: "DL-0438",
    actionRequired: true,
    iconType: "payment",
  },
  {
    id: "notification-system-update",
    title: "Security Settings Updated",
    body: "Your notification preferences were updated successfully.",
    timeLabel: "Sat, 12:12 PM",
    dateGroup: "older",
    category: "system",
    unread: false,
    iconType: "system",
  },
];
