import type { BuyerPayment, BuyerPaymentStats } from "@/components/dashboard/buyer/payments/buyer-payments.types";

export const buyerPaymentStats: BuyerPaymentStats = {
  escrowBalance: 428500,
  totalSettledYtd: 1842000.5,
  upcomingPayouts: 125750,
};

export const buyerPayments: BuyerPayment[] = [
  {
    id: "#PAY-9921",
    contractId: "#CTR-804",
    recipientName: "Green Valley Organic Co.",
    recipientSubtitle: "Verified Tier 1 Supplier",
    recipientIconType: "leaf",
    amount: 85400,
    status: "escrow",
    authDate: "Oct 24, 2023",
  },
  {
    id: "#PAY-9918",
    contractId: "#CTR-792",
    recipientName: "AgriTech Systems Ltd.",
    recipientSubtitle: "Equipment Lease",
    recipientIconType: "equipment",
    amount: 42150,
    status: "released",
    authDate: "Oct 22, 2023",
  },
  {
    id: "#PAY-9915",
    contractId: "#CTR-785",
    recipientName: "SwiftLogistics Global",
    recipientSubtitle: "Logistics Partner",
    recipientIconType: "logistics",
    amount: 12000,
    status: "pending",
    authDate: "Oct 20, 2023",
  },
  {
    id: "#PAY-9912",
    contractId: "#CTR-770",
    recipientName: "Al-Nour Farm",
    recipientSubtitle: "Tomatoes Batch T-23",
    recipientIconType: "leaf",
    amount: 28750,
    status: "escrow",
    authDate: "Oct 18, 2023",
  },
  {
    id: "#PAY-9909",
    contractId: "#CTR-766",
    recipientName: "FreshMart Packaging",
    recipientSubtitle: "Crate Supply",
    recipientIconType: "equipment",
    amount: 19600,
    status: "released",
    authDate: "Oct 15, 2023",
  },
  {
    id: "#PAY-9904",
    contractId: "#CTR-758",
    recipientName: "Green Fields Co.",
    recipientSubtitle: "Wheat Shipment",
    recipientIconType: "leaf",
    amount: 64800,
    status: "pending",
    authDate: "Oct 12, 2023",
  },
  {
    id: "#PAY-9901",
    contractId: "#CTR-744",
    recipientName: "Oasis Irrigation Works",
    recipientSubtitle: "Irrigation Parts",
    recipientIconType: "equipment",
    amount: 33650,
    status: "released",
    authDate: "Oct 09, 2023",
  },
  {
    id: "#PAY-9898",
    contractId: "#CTR-731",
    recipientName: "Harvest Route Logistics",
    recipientSubtitle: "Cold Chain Partner",
    recipientIconType: "logistics",
    amount: 22800,
    status: "escrow",
    authDate: "Oct 06, 2023",
  },
  {
    id: "#PAY-9892",
    contractId: "#CTR-718",
    recipientName: "Aegean Orchards",
    recipientSubtitle: "Kalamata Olive Supply",
    recipientIconType: "leaf",
    amount: 51200,
    status: "released",
    authDate: "Oct 02, 2023",
  },
  {
    id: "#PAY-9887",
    contractId: "#CTR-701",
    recipientName: "Citrus Grove Collective",
    recipientSubtitle: "Meyer Lemons Batch L-18",
    recipientIconType: "leaf",
    amount: 17750,
    status: "escrow",
    authDate: "Sep 28, 2023",
  },
  {
    id: "#PAY-9881",
    contractId: "#CTR-690",
    recipientName: "Saudi Hydro Systems",
    recipientSubtitle: "Pump Maintenance",
    recipientIconType: "equipment",
    amount: 14400,
    status: "pending",
    authDate: "Sep 24, 2023",
  },
  {
    id: "#PAY-9876",
    contractId: "#CTR-681",
    recipientName: "Golden Fields Co.",
    recipientSubtitle: "Durum Wheat Contract",
    recipientIconType: "leaf",
    amount: 93000,
    status: "released",
    authDate: "Sep 20, 2023",
  },
];
