import type { AdminQualityOfficer, DealNeedingAssignment } from "@/components/dashboard/admin/quality-officers/admin-quality-officers.types";

export const adminQualityOfficers: AdminQualityOfficer[] = [
  {
    averageRating: 4.8,
    completedInspections: 128,
    coverageAreas: ["Al Ahsa", "Al Hofuf", "Al Qatif"],
    distanceFromFarmKm: 12,
    id: "qo-1",
    name: "Abdullah Al Mutairi",
    phone: "+966 50 123 4567",
    status: "available",
  },
  {
    averageRating: 4.6,
    completedInspections: 97,
    coverageAreas: ["Riyadh", "Al Kharj", "Al Majmaah"],
    distanceFromFarmKm: 42,
    id: "qo-2",
    name: "Faisal Al Otaibi",
    phone: "+966 55 987 6543",
    status: "busy",
  },
  {
    averageRating: 4.7,
    completedInspections: 85,
    coverageAreas: ["Jeddah", "Taif", "Al Bahah"],
    distanceFromFarmKm: 58,
    id: "qo-3",
    name: "Mohammed Al Harbi",
    phone: "+966 54 321 7890",
    status: "available",
  },
  {
    averageRating: 4.5,
    completedInspections: 64,
    coverageAreas: ["Hail", "Buraidah", "Unaizah"],
    distanceFromFarmKm: 66,
    id: "qo-4",
    name: "Sami Al Shammari",
    phone: "+966 53 654 3210",
    status: "busy",
  },
  {
    averageRating: 4.9,
    completedInspections: 112,
    coverageAreas: ["Dammam", "Khobar", "Jubail"],
    distanceFromFarmKm: 18,
    id: "qo-5",
    name: "Khalid Al Dossari",
    phone: "+966 50 222 3344",
    status: "available",
  },
  {
    averageRating: 4.2,
    completedInspections: 38,
    coverageAreas: ["Abha", "Khamis Mushait", "Najran"],
    distanceFromFarmKm: 84,
    id: "qo-6",
    name: "Nasser Al Qahtani",
    phone: "+966 56 777 8899",
    status: "suspended",
  },
];

export const dealsNeedingAssignment: DealNeedingAssignment[] = [
  {
    dealId: "#D-2025-1542",
    dealValue: 25000,
    farmLocation: "Al Sa'adah Farm, Al Ahsa",
    id: "assignment-deal-1542",
    priority: "high",
    product: "Tomatoes",
    requiredDate: "May 26, 2025",
  },
  {
    dealId: "#D-2025-1538",
    dealValue: 18000,
    farmLocation: "Al Noor Farm, Al Qassim",
    id: "assignment-deal-1538",
    product: "Chili Peppers",
    requiredDate: "May 27, 2025",
  },
  {
    dealId: "#D-2025-1531",
    dealValue: 32000,
    farmLocation: "Al Waha Farm, Tabuk",
    id: "assignment-deal-1531",
    product: "Apples",
    requiredDate: "May 28, 2025",
  },
  {
    dealId: "#D-2025-1524",
    dealValue: 20500,
    farmLocation: "Al Khair Farm, Al Jouf",
    id: "assignment-deal-1524",
    product: "Dates",
    requiredDate: "May 30, 2025",
  },
];
