import type { BuyerFavoriteListing } from "@/components/dashboard/buyer/favorites/buyer-favorites.types";

const tomatoImage = "/images/farmer/listings/tomatoes-listing.jpg";
const wheatImage = "/images/farmer/listings/wheat-listing.jpg";
const olivesImage = "/images/farmer/listings/green-olives-listing.jpg";
// TODO: Replace mock product image with backend image when API is ready.
const fallbackImage = "/images/farmer/create-listing/placeholders/listing-photo-placeholder-1.jpg";

export const buyerFavoriteListings: BuyerFavoriteListing[] = [
  {
    category: "Vegetables",
    currency: "$",
    id: "premium-roma-tomatoes",
    image: tomatoImage,
    name: "Premium Roma Tomatoes",
    price: 1.2,
    rating: 4.8,
    reviews: 120,
    status: "available",
    supplier: "Harvest Collective",
    unit: "kg",
  },
  {
    category: "Grains",
    currency: "$",
    id: "golden-durum-wheat",
    image: wheatImage,
    name: "Golden Durum Wheat",
    price: 340,
    rating: 4.9,
    reviews: 350,
    status: "low-stock",
    supplier: "Midwest Plains Ltd",
    unit: "ton",
  },
  {
    category: "Olives",
    currency: "$",
    id: "organic-kalamata-olives",
    image: olivesImage,
    name: "Organic Kalamata Olives",
    price: 5.45,
    rating: 4.7,
    reviews: 85,
    status: "expiring-soon",
    supplier: "Aegean Orchards",
    unit: "jar",
  },
  {
    category: "Vegetables",
    currency: "$",
    id: "hydroponic-butterhead",
    image: fallbackImage,
    name: "Hydroponic Butterhead",
    price: 0.85,
    rating: 4.9,
    reviews: 42,
    status: "available",
    supplier: "Urban Greens",
    unit: "head",
  },
  {
    category: "Coffee",
    currency: "$",
    id: "arabica-coffee-beans",
    image: "/images/farmer/create-listing/placeholders/listing-photo-placeholder-2.jpg",
    name: "Arabica Coffee Beans",
    price: 12.5,
    rating: 4.6,
    reviews: 94,
    status: "available",
    supplier: "Highland Growers",
    unit: "kg",
  },
  {
    category: "Fruits",
    currency: "$",
    id: "seedless-meyer-lemons",
    image: "/images/farmer/create-listing/placeholders/listing-photo-placeholder-3.jpg",
    name: "Seedless Meyer Lemons",
    price: 2.1,
    rating: 4.8,
    reviews: 55,
    status: "available",
    supplier: "Citrus Grove Collective",
    unit: "kg",
  },
  {
    category: "Fruits",
    currency: "$",
    id: "medjool-dates",
    image: "/images/farmer/create-listing/placeholders/listing-photo-placeholder-4.jpg",
    name: "Premium Medjool Dates",
    price: 8.75,
    rating: 4.7,
    reviews: 76,
    status: "available",
    supplier: "Desert Palm Farms",
    unit: "kg",
  },
  {
    category: "Vegetables",
    currency: "$",
    id: "english-cucumbers",
    image: "/images/farmer/create-listing/placeholders/listing-photo-placeholder-5.jpg",
    name: "English Cucumbers",
    price: 1.4,
    rating: 4.5,
    reviews: 63,
    status: "low-stock",
    supplier: "Greenhouse Supply Co.",
    unit: "kg",
  },
  {
    category: "Grains",
    currency: "$",
    id: "pearl-barley",
    image: wheatImage,
    name: "Pearl Barley",
    price: 210,
    rating: 4.6,
    reviews: 118,
    status: "available",
    supplier: "North Valley Grain",
    unit: "ton",
  },
  {
    category: "Olives",
    currency: "$",
    id: "green-olive-crates",
    image: olivesImage,
    name: "Green Olive Crates",
    price: 4.95,
    rating: 4.8,
    reviews: 101,
    status: "available",
    supplier: "Levant Grove",
    unit: "kg",
  },
  {
    category: "Coffee",
    currency: "$",
    id: "washed-ethiopian-coffee",
    image: "/images/farmer/create-listing/placeholders/listing-photo-placeholder-6.jpg",
    name: "Washed Ethiopian Coffee",
    price: 14.25,
    rating: 4.9,
    reviews: 137,
    status: "expiring-soon",
    supplier: "Summit Roasters",
    unit: "kg",
  },
  {
    category: "Fruits",
    currency: "$",
    id: "blood-oranges",
    image: "/images/farmer/create-listing/placeholders/listing-photo-placeholder-7.jpg",
    name: "Blood Oranges",
    price: 2.35,
    rating: 4.6,
    reviews: 48,
    status: "available",
    supplier: "Citrus Grove Collective",
    unit: "kg",
  },
];
