import type { BuyerDisputeCase, BuyerDisputeStats, ResolutionEfficiencyPoint } from "@/components/dashboard/buyer/disputes/buyer-disputes.types";

export const buyerDisputeStats: BuyerDisputeStats = {
  openDisputes: 14,
  resolvedCases: 128,
  averageResolutionDays: 4.2,
};

export const buyerDisputeCases: BuyerDisputeCase[] = [
  {
    id: "#DIS-8921",
    contractTitle: "Wheat Shipment Q4",
    contractId: "CTR-00421",
    merchant: "Global Grains Inc.",
    reason: "Quality non-compliance",
    status: "under-review",
    priority: "urgent",
  },
  {
    id: "#DIS-8922",
    contractTitle: "Soybean Logistics",
    contractId: "CTR-00985",
    merchant: "TransAgro Logistics",
    reason: "Delayed port clearance",
    status: "mediation",
    priority: "medium",
  },
  {
    id: "#DIS-8923",
    contractTitle: "Fertilizer Supply B",
    contractId: "CTR-01022",
    merchant: "NutriCrop Ltd.",
    reason: "Partial payment dispute",
    status: "resolved",
    priority: "low",
  },
  {
    id: "#DIS-8924",
    contractTitle: "Organic Corn X",
    contractId: "CTR-00771",
    merchant: "BioFarms Co.",
    reason: "Weight/Volume mismatch",
    status: "under-review",
    priority: "high",
  },
  {
    id: "#DIS-8925",
    contractTitle: "Tomato Supply Batch",
    contractId: "CTR-00816",
    merchant: "Al-Nour Farm",
    reason: "Late delivery notice",
    status: "mediation",
    priority: "medium",
  },
  {
    id: "#DIS-8926",
    contractTitle: "Irrigation Parts",
    contractId: "CTR-01087",
    merchant: "Oasis Irrigation Works",
    reason: "Incomplete shipment",
    status: "under-review",
    priority: "high",
  },
  {
    id: "#DIS-8927",
    contractTitle: "Cold Chain Delivery",
    contractId: "CTR-01112",
    merchant: "Harvest Route Logistics",
    reason: "Temperature variance",
    status: "resolved",
    priority: "low",
  },
  {
    id: "#DIS-8928",
    contractTitle: "Packaging Order C",
    contractId: "CTR-01138",
    merchant: "GreenPack Arabia",
    reason: "Invoice discrepancy",
    status: "mediation",
    priority: "medium",
  },
  {
    id: "#DIS-8929",
    contractTitle: "Premium Wheat Lot",
    contractId: "CTR-01144",
    merchant: "Midwest Grain Masters",
    reason: "Certification mismatch",
    status: "resolved",
    priority: "low",
  },
  {
    id: "#DIS-8930",
    contractTitle: "Organic Blend Inputs",
    contractId: "CTR-01167",
    merchant: "Fresh Inputs Trading",
    reason: "Short quantity received",
    status: "under-review",
    priority: "urgent",
  },
  {
    id: "#DIS-8931",
    contractTitle: "Hydro Pump Contract",
    contractId: "CTR-01183",
    merchant: "Saudi Hydro Systems",
    reason: "Warranty clause conflict",
    status: "mediation",
    priority: "high",
  },
  {
    id: "#DIS-8932",
    contractTitle: "Carton Supply Run",
    contractId: "CTR-01201",
    merchant: "Palm Grove Packaging",
    reason: "Damaged packaging",
    status: "resolved",
    priority: "low",
  },
  {
    id: "#DIS-8933",
    contractTitle: "Olive Oil Purchase",
    contractId: "CTR-01218",
    merchant: "Aegean Orchards",
    reason: "Grade specification dispute",
    status: "under-review",
    priority: "medium",
  },
  {
    id: "#DIS-8934",
    contractTitle: "Lemon Export Lot",
    contractId: "CTR-01239",
    merchant: "Citrus Grove Collective",
    reason: "Customs document delay",
    status: "mediation",
    priority: "high",
  },
];

export const resolutionEfficiencyData: ResolutionEfficiencyPoint[] = [
  { day: "MON", activity: 35, closed: 18 },
  { day: "TUE", activity: 55, closed: 42 },
  { day: "WED", activity: 40, closed: 12 },
  { day: "THU", activity: 75, closed: 68 },
  { day: "FRI", activity: 62, closed: 34 },
  { day: "SAT", activity: 85, closed: 76 },
  { day: "SUN", activity: 50, closed: 18 },
];
